# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccountDocumentResponsibleResponseAccountDocumentResponsibleType(str, Enum):
    """
    Tipo de responsável
    """

    """
    allowed enum values
    """
    ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT = 'ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT'
    ASAAS_ACCOUNT_OWNER_EMANCIPATION_AGE = 'ASAAS_ACCOUNT_OWNER_EMANCIPATION_AGE'
    ASAAS_ACCOUNT_OWNER = 'ASAAS_ACCOUNT_OWNER'
    ASSOCIATION = 'ASSOCIATION'
    BANK_ACCOUNT_OWNER_EMANCIPATION_AGE = 'BANK_ACCOUNT_OWNER_EMANCIPATION_AGE'
    BANK_ACCOUNT_OWNER = 'BANK_ACCOUNT_OWNER'
    CUSTOM = 'CUSTOM'
    DIRECTOR = 'DIRECTOR'
    INDIVIDUAL_COMPANY = 'INDIVIDUAL_COMPANY'
    LIMITED_COMPANY = 'LIMITED_COMPANY'
    MEI = 'MEI'
    PARTNER = 'PARTNER'
    POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountDocumentResponsibleResponseAccountDocumentResponsibleType from a JSON string"""
        return cls(json.loads(json_str))


