# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccountDocumentSaveRequestAccountDocumentType(str, Enum):
    """
    Tipo de documento
    """

    """
    allowed enum values
    """
    ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT = 'ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT'
    CUSTOM = 'CUSTOM'
    EMANCIPATION_OF_MINORS = 'EMANCIPATION_OF_MINORS'
    ENTREPRENEUR_REQUIREMENT = 'ENTREPRENEUR_REQUIREMENT'
    IDENTIFICATION_SELFIE = 'IDENTIFICATION_SELFIE'
    IDENTIFICATION = 'IDENTIFICATION'
    INVOICE = 'INVOICE'
    MEI_CERTIFICATE = 'MEI_CERTIFICATE'
    MINUTES_OF_CONSTITUTION = 'MINUTES_OF_CONSTITUTION'
    MINUTES_OF_ELECTION = 'MINUTES_OF_ELECTION'
    POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY'
    SOCIAL_CONTRACT = 'SOCIAL_CONTRACT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountDocumentSaveRequestAccountDocumentType from a JSON string"""
        return cls(json.loads(json_str))


