# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.account_save_request_company_type import AccountSaveRequestCompanyType
from asaas.models.webhook_config_save_request_dto import WebhookConfigSaveRequestDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountSaveRequestDTO(BaseModel):
    """
    AccountSaveRequestDTO
    """ # noqa: E501
    name: StrictStr = Field(description="Nome da subconta")
    email: StrictStr = Field(description="Email da subconta")
    login_email: Optional[StrictStr] = Field(default=None, description="Email para login da subconta, caso não informado será utilizado o email da subconta", alias="loginEmail")
    cpf_cnpj: StrictStr = Field(description="CPF ou CNPJ do proprietário da subconta", alias="cpfCnpj")
    birth_date: Optional[date] = Field(default=None, description="Data de nascimento (somente quando Pessoa Física)", alias="birthDate")
    company_type: Optional[AccountSaveRequestCompanyType] = Field(default=None, alias="companyType")
    phone: Optional[StrictStr] = Field(default=None, description="Telefone Fixo")
    mobile_phone: StrictStr = Field(description="Telefone Celular", alias="mobilePhone")
    site: Optional[StrictStr] = Field(default=None, description="URL of the subbacount website")
    income_value: Union[StrictFloat, StrictInt] = Field(description="Faturamento/Renda mensal", alias="incomeValue")
    address: StrictStr = Field(description="Logradouro")
    address_number: StrictStr = Field(description="Número do endereço", alias="addressNumber")
    complement: Optional[StrictStr] = Field(default=None, description="Complemento do endereço")
    province: StrictStr = Field(description="Bairro")
    postal_code: StrictStr = Field(description="CEP do endereço", alias="postalCode")
    webhooks: Optional[List[WebhookConfigSaveRequestDTO]] = Field(default=None, description="Array com as configurações de Webhooks desejadas")
    __properties: ClassVar[List[str]] = ["name", "email", "loginEmail", "cpfCnpj", "birthDate", "companyType", "phone", "mobilePhone", "site", "incomeValue", "address", "addressNumber", "complement", "province", "postalCode", "webhooks"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountSaveRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in webhooks (list)
        _items = []
        if self.webhooks:
            for _item_webhooks in self.webhooks:
                if _item_webhooks:
                    _items.append(_item_webhooks.to_dict())
            _dict['webhooks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountSaveRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "email": obj.get("email"),
            "loginEmail": obj.get("loginEmail"),
            "cpfCnpj": obj.get("cpfCnpj"),
            "birthDate": obj.get("birthDate"),
            "companyType": obj.get("companyType"),
            "phone": obj.get("phone"),
            "mobilePhone": obj.get("mobilePhone"),
            "site": obj.get("site"),
            "incomeValue": obj.get("incomeValue"),
            "address": obj.get("address"),
            "addressNumber": obj.get("addressNumber"),
            "complement": obj.get("complement"),
            "province": obj.get("province"),
            "postalCode": obj.get("postalCode"),
            "webhooks": [WebhookConfigSaveRequestDTO.from_dict(_item) for _item in obj["webhooks"]] if obj.get("webhooks") is not None else None
        })
        return _obj


