# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.anticipation_get_response_anticipation_status import AnticipationGetResponseAnticipationStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AnticipationGetResponseDTO(BaseModel):
    """
    AnticipationGetResponseDTO
    """ # noqa: E501
    object: Optional[StrictStr] = Field(default=None, description="Tipo de objeto")
    id: Optional[StrictStr] = Field(default=None, description="Identificador único da antecipação no Asaas")
    installment: Optional[StrictStr] = Field(default=None, description="Identificador único do parcelamento a ser antecipado")
    payment: Optional[StrictStr] = Field(default=None, description="Identificador único da cobrança a ser antecipada.")
    status: Optional[AnticipationGetResponseAnticipationStatus] = None
    anticipation_date: Optional[date] = Field(default=None, description="Data de solicitação da antecipação", alias="anticipationDate")
    due_date: Optional[date] = Field(default=None, description="Data de vencimento da solicitação", alias="dueDate")
    request_date: Optional[date] = Field(default=None, description="Data de solicitação da antecipação", alias="requestDate")
    fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Taxa de antecipação")
    anticipation_days: Optional[StrictInt] = Field(default=None, description="Quantidade de dias que foram antecipados", alias="anticipationDays")
    net_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor líquido descontada a taxa de antecipação", alias="netValue")
    total_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor total da cobrança a ser antecipada", alias="totalValue")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor da antecipação")
    denial_observation: Optional[StrictStr] = Field(default=None, description="Motivo de rejeição da antecipação", alias="denialObservation")
    __properties: ClassVar[List[str]] = ["object", "id", "installment", "payment", "status", "anticipationDate", "dueDate", "requestDate", "fee", "anticipationDays", "netValue", "totalValue", "value", "denialObservation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnticipationGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnticipationGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "installment": obj.get("installment"),
            "payment": obj.get("payment"),
            "status": obj.get("status"),
            "anticipationDate": obj.get("anticipationDate"),
            "dueDate": obj.get("dueDate"),
            "requestDate": obj.get("requestDate"),
            "fee": obj.get("fee"),
            "anticipationDays": obj.get("anticipationDays"),
            "netValue": obj.get("netValue"),
            "totalValue": obj.get("totalValue"),
            "value": obj.get("value"),
            "denialObservation": obj.get("denialObservation")
        })
        return _obj


