# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.bill_simulate_bank_slip_info_response_dto import BillSimulateBankSlipInfoResponseDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BillSimulateResponseDTO(BaseModel):
    """
    BillSimulateResponseDTO
    """ # noqa: E501
    minimum_schedule_date: Optional[date] = Field(default=None, description="Data mínima permitida para agendamento", alias="minimumScheduleDate")
    fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Taxa cobrada no pagamento da conta")
    bank_slip_info: Optional[BillSimulateBankSlipInfoResponseDTO] = Field(default=None, alias="bankSlipInfo")
    __properties: ClassVar[List[str]] = ["minimumScheduleDate", "fee", "bankSlipInfo"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillSimulateResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bank_slip_info
        if self.bank_slip_info:
            _dict['bankSlipInfo'] = self.bank_slip_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillSimulateResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "minimumScheduleDate": obj.get("minimumScheduleDate"),
            "fee": obj.get("fee"),
            "bankSlipInfo": BillSimulateBankSlipInfoResponseDTO.from_dict(obj["bankSlipInfo"]) if obj.get("bankSlipInfo") is not None else None
        })
        return _obj


