# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.bill_get_response_bill_status import BillGetResponseBillStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BillGetResponseDTO(BaseModel):
    """
    BillGetResponseDTO
    """ # noqa: E501
    object: Optional[StrictStr] = Field(default=None, description="Tipo de objeto")
    id: Optional[StrictStr] = Field(default=None, description="Identificador único do pagamento de conta no Asaas")
    status: Optional[BillGetResponseBillStatus] = None
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor a ser pago")
    discount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Desconto atribuído ao pagamento")
    interest: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Juros atribuído ao pagamento")
    fine: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Multa atribuída ao pagamento")
    identification_field: Optional[StrictStr] = Field(default=None, description="Linha digitável do boleto a ser pago", alias="identificationField")
    due_date: Optional[date] = Field(default=None, description="Data de vencimento da cobrança", alias="dueDate")
    schedule_date: Optional[date] = Field(default=None, description="Data de agendamento do pagamento", alias="scheduleDate")
    payment_date: Optional[date] = Field(default=None, description="Data em que o pagamento foi efetivado", alias="paymentDate")
    fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Taxa do Asaas para o pagamento de conta")
    description: Optional[StrictStr] = Field(default=None, description="Descrição do pagamento de conta")
    company_name: Optional[StrictStr] = Field(default=None, description="Empresa/Órgão emissor da cobrança", alias="companyName")
    transaction_receipt_url: Optional[StrictStr] = Field(default=None, description="Comprovante do pagamento de conta", alias="transactionReceiptUrl")
    can_be_cancelled: Optional[StrictBool] = Field(default=None, description="Se o pagamento pode ser cancelado", alias="canBeCancelled")
    external_reference: Optional[StrictStr] = Field(default=None, description="Identificador do boleto no seu sistema", alias="externalReference")
    fail_reasons: Optional[List[StrictStr]] = Field(default=None, description="Lista com motivos de falha no pagamento", alias="failReasons")
    __properties: ClassVar[List[str]] = ["object", "id", "status", "value", "discount", "interest", "fine", "identificationField", "dueDate", "scheduleDate", "paymentDate", "fee", "description", "companyName", "transactionReceiptUrl", "canBeCancelled", "externalReference", "failReasons"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "status": obj.get("status"),
            "value": obj.get("value"),
            "discount": obj.get("discount"),
            "interest": obj.get("interest"),
            "fine": obj.get("fine"),
            "identificationField": obj.get("identificationField"),
            "dueDate": obj.get("dueDate"),
            "scheduleDate": obj.get("scheduleDate"),
            "paymentDate": obj.get("paymentDate"),
            "fee": obj.get("fee"),
            "description": obj.get("description"),
            "companyName": obj.get("companyName"),
            "transactionReceiptUrl": obj.get("transactionReceiptUrl"),
            "canBeCancelled": obj.get("canBeCancelled"),
            "externalReference": obj.get("externalReference"),
            "failReasons": obj.get("failReasons")
        })
        return _obj


