# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BillSaveRequestDTO(BaseModel):
    """
    BillSaveRequestDTO
    """ # noqa: E501
    identification_field: StrictStr = Field(description="Linha digitável do boleto", alias="identificationField")
    schedule_date: Optional[StrictStr] = Field(default=None, description="Data de agendamento do pagamento", alias="scheduleDate")
    description: Optional[StrictStr] = Field(default=None, description="Descrição do pagamento de conta")
    discount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Desconto atribuído ao pagamento")
    interest: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Juros atribuído ao pagamento")
    fine: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Multa atribuída ao pagamento")
    due_date: Optional[date] = Field(default=None, description="Data de vencimento da conta caso seja do tipo que não possui essa informação", alias="dueDate")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor da conta caso seja do tipo que não possui essa informação (Ex: faturas de cartão de crédito)")
    external_reference: Optional[StrictStr] = Field(default=None, description="Identificador do boleto no seu sistema", alias="externalReference")
    __properties: ClassVar[List[str]] = ["identificationField", "scheduleDate", "description", "discount", "interest", "fine", "dueDate", "value", "externalReference"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillSaveRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillSaveRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identificationField": obj.get("identificationField"),
            "scheduleDate": obj.get("scheduleDate"),
            "description": obj.get("description"),
            "discount": obj.get("discount"),
            "interest": obj.get("interest"),
            "fine": obj.get("fine"),
            "dueDate": obj.get("dueDate"),
            "value": obj.get("value"),
            "externalReference": obj.get("externalReference")
        })
        return _obj


