# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CheckoutSessionSubscriptionCycle(str, Enum):
    """
    Periodicidade da cobrança
    """

    """
    allowed enum values
    """
    WEEKLY = 'WEEKLY'
    BIWEEKLY = 'BIWEEKLY'
    MONTHLY = 'MONTHLY'
    BIMONTHLY = 'BIMONTHLY'
    QUARTERLY = 'QUARTERLY'
    SEMIANNUALLY = 'SEMIANNUALLY'
    YEARLY = 'YEARLY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckoutSessionSubscriptionCycle from a JSON string"""
        return cls(json.loads(json_str))


