# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreditCardHolderInfoRequestDTO(BaseModel):
    """
    Informações do titular do cartão de crédito
    """ # noqa: E501
    name: StrictStr = Field(description="Nome do titular do cartão")
    email: StrictStr = Field(description="Email do titular do cartão")
    cpf_cnpj: StrictStr = Field(description="CPF ou CNPJ do titular do cartão", alias="cpfCnpj")
    postal_code: StrictStr = Field(description="CEP do titular do cartão", alias="postalCode")
    address_number: StrictStr = Field(description="Número do endereço do titular do cartão", alias="addressNumber")
    address_complement: Optional[StrictStr] = Field(default=None, description="Complemento do endereço do titular do cartão", alias="addressComplement")
    phone: StrictStr = Field(description="Telefone com DDD do titular do cartão")
    mobile_phone: Optional[StrictStr] = Field(default=None, description="Celular do titular do cartão", alias="mobilePhone")
    __properties: ClassVar[List[str]] = ["name", "email", "cpfCnpj", "postalCode", "addressNumber", "addressComplement", "phone", "mobilePhone"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreditCardHolderInfoRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreditCardHolderInfoRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "email": obj.get("email"),
            "cpfCnpj": obj.get("cpfCnpj"),
            "postalCode": obj.get("postalCode"),
            "addressNumber": obj.get("addressNumber"),
            "addressComplement": obj.get("addressComplement"),
            "phone": obj.get("phone"),
            "mobilePhone": obj.get("mobilePhone")
        })
        return _obj


