# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomerUpdateRequestDTO(BaseModel):
    """
    CustomerUpdateRequestDTO
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Nome do cliente")
    cpf_cnpj: Optional[StrictStr] = Field(default=None, description="CPF ou CNPJ do cliente", alias="cpfCnpj")
    email: Optional[StrictStr] = Field(default=None, description="Email do cliente")
    phone: Optional[StrictStr] = Field(default=None, description="Fone fixo")
    mobile_phone: Optional[StrictStr] = Field(default=None, description="Fone celular", alias="mobilePhone")
    address: Optional[StrictStr] = Field(default=None, description="Logradouro")
    address_number: Optional[StrictStr] = Field(default=None, description="Número do endereço", alias="addressNumber")
    complement: Optional[StrictStr] = Field(default=None, description="Complemento do endereço")
    province: Optional[StrictStr] = Field(default=None, description="Bairro")
    postal_code: Optional[StrictStr] = Field(default=None, description="CEP do endereço", alias="postalCode")
    external_reference: Optional[StrictStr] = Field(default=None, description="Identificador do cliente no seu sistema", alias="externalReference")
    notification_disabled: Optional[StrictBool] = Field(default=None, description="true para desabilitar o envio de notificações de cobrança", alias="notificationDisabled")
    additional_emails: Optional[StrictStr] = Field(default=None, description="Emails adicionais para envio de notificações de cobrança separados por \",\"", alias="additionalEmails")
    municipal_inscription: Optional[StrictStr] = Field(default=None, description="Inscrição municipal do cliente", alias="municipalInscription")
    state_inscription: Optional[StrictStr] = Field(default=None, description="Inscrição estadual do cliente", alias="stateInscription")
    observations: Optional[StrictStr] = Field(default=None, description="Observações adicionais")
    group_name: Optional[StrictStr] = Field(default=None, description="Nome do grupo ao qual o cliente pertence", alias="groupName")
    company: Optional[StrictStr] = Field(default=None, description="Empresa")
    foreign_customer: Optional[StrictBool] = Field(default=None, description="informe true caso seja pagador estrangeiro", alias="foreignCustomer")
    __properties: ClassVar[List[str]] = ["name", "cpfCnpj", "email", "phone", "mobilePhone", "address", "addressNumber", "complement", "province", "postalCode", "externalReference", "notificationDisabled", "additionalEmails", "municipalInscription", "stateInscription", "observations", "groupName", "company", "foreignCustomer"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerUpdateRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerUpdateRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "cpfCnpj": obj.get("cpfCnpj"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "mobilePhone": obj.get("mobilePhone"),
            "address": obj.get("address"),
            "addressNumber": obj.get("addressNumber"),
            "complement": obj.get("complement"),
            "province": obj.get("province"),
            "postalCode": obj.get("postalCode"),
            "externalReference": obj.get("externalReference"),
            "notificationDisabled": obj.get("notificationDisabled"),
            "additionalEmails": obj.get("additionalEmails"),
            "municipalInscription": obj.get("municipalInscription"),
            "stateInscription": obj.get("stateInscription"),
            "observations": obj.get("observations"),
            "groupName": obj.get("groupName"),
            "company": obj.get("company"),
            "foreignCustomer": obj.get("foreignCustomer")
        })
        return _obj


