# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.financial_transaction_get_response_financial_transaction_type import FinancialTransactionGetResponseFinancialTransactionType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FinancialTransactionGetResponseDTO(BaseModel):
    """
    Lista de objetos
    """ # noqa: E501
    object: Optional[StrictStr] = Field(default=None, description="Tipo de objeto")
    id: Optional[StrictStr] = Field(default=None, description="Identificador único da transação no Asaas")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor da transação")
    balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor em conta no momento da transação")
    type: Optional[FinancialTransactionGetResponseFinancialTransactionType] = None
    var_date: Optional[date] = Field(default=None, description="Data da transação", alias="date")
    description: Optional[StrictStr] = Field(default=None, description="Descrição da transação")
    payment_id: Optional[StrictStr] = Field(default=None, description="Identificador da cobrança (Se houver)", alias="paymentId")
    split_id: Optional[StrictStr] = Field(default=None, description="Identificador do split (Se houver)", alias="splitId")
    transfer_id: Optional[StrictStr] = Field(default=None, description="Identificador da transferência (Se houver)", alias="transferId")
    anticipation_id: Optional[StrictStr] = Field(default=None, description="Identificador da antecipação (Se houver)", alias="anticipationId")
    bill_id: Optional[StrictStr] = Field(default=None, description="Identificador do pagamento de contas (Se houver)", alias="billId")
    invoice_id: Optional[StrictStr] = Field(default=None, description="Identificador da nota fiscal (Se houver)", alias="invoiceId")
    payment_dunning_id: Optional[StrictStr] = Field(default=None, description="Identificador da negativação (Se houver)", alias="paymentDunningId")
    credit_bureau_report_id: Optional[StrictStr] = Field(default=None, description="Identificador da consulta Serasa (Se houver)", alias="creditBureauReportId")
    __properties: ClassVar[List[str]] = ["object", "id", "value", "balance", "type", "date", "description", "paymentId", "splitId", "transferId", "anticipationId", "billId", "invoiceId", "paymentDunningId", "creditBureauReportId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FinancialTransactionGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FinancialTransactionGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "value": obj.get("value"),
            "balance": obj.get("balance"),
            "type": obj.get("type"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "paymentId": obj.get("paymentId"),
            "splitId": obj.get("splitId"),
            "transferId": obj.get("transferId"),
            "anticipationId": obj.get("anticipationId"),
            "billId": obj.get("billId"),
            "invoiceId": obj.get("invoiceId"),
            "paymentDunningId": obj.get("paymentDunningId"),
            "creditBureauReportId": obj.get("creditBureauReportId")
        })
        return _obj


