# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asaas.models.fiscal_info_municipal_options_get_response_enotas_tipo_autenticacao import FiscalInfoMunicipalOptionsGetResponseEnotasTipoAutenticacao
from asaas.models.fiscal_info_municipal_options_national_portal_tax_calculation_regime_dto import FiscalInfoMunicipalOptionsNationalPortalTaxCalculationRegimeDTO
from asaas.models.fiscal_info_municipal_options_special_tax_regimes_dto import FiscalInfoMunicipalOptionsSpecialTaxRegimesDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FiscalInfoMunicipalOptionsGetResponseDTO(BaseModel):
    """
    FiscalInfoMunicipalOptionsGetResponseDTO
    """ # noqa: E501
    authentication_type: Optional[FiscalInfoMunicipalOptionsGetResponseEnotasTipoAutenticacao] = Field(default=None, alias="authenticationType")
    supports_cancellation: Optional[StrictBool] = Field(default=True, description="Suporta ou não o cancelamento de notas fiscais automaticamente na sua prefeitura", alias="supportsCancellation")
    uses_special_tax_regimes: Optional[StrictBool] = Field(default=True, description="Necessário informar ou não o regime especial de tributação. Caso utilize, informe-o no campo `specialTaxRegime` do **Criar ou atualizar informações fiscais** de acordo com as opções retornadas na lista `specialTaxRegimesList`", alias="usesSpecialTaxRegimes")
    uses_service_list_item: Optional[StrictBool] = Field(default=True, description="Necessário informar ou não o item da lista de serviço", alias="usesServiceListItem")
    special_tax_regimes_list: Optional[List[FiscalInfoMunicipalOptionsSpecialTaxRegimesDTO]] = Field(default=None, description="Opções de regime especial de tributação", alias="specialTaxRegimesList")
    national_portal_tax_calculation_regime_list: Optional[List[FiscalInfoMunicipalOptionsNationalPortalTaxCalculationRegimeDTO]] = Field(default=None, description="Opções de regime de apuração tributária pelo Simples Nacional", alias="nationalPortalTaxCalculationRegimeList")
    national_portal_tax_calculation_regime_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre o regime de apuração tributária pelo Simples Nacional", alias="nationalPortalTaxCalculationRegimeHelp")
    municipal_inscription_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre formato da inscrição municipal", alias="municipalInscriptionHelp")
    special_tax_regime_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre o regime especial de tributação", alias="specialTaxRegimeHelp")
    service_list_item_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre formato do item da lista de serviço", alias="serviceListItemHelp")
    digital_certificated_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre certificado digital", alias="digitalCertificatedHelp")
    access_token_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre token", alias="accessTokenHelp")
    municipal_service_code_help: Optional[StrictStr] = Field(default=None, description="Explicação sobre formato do código de serviço municipal", alias="municipalServiceCodeHelp")
    __properties: ClassVar[List[str]] = ["authenticationType", "supportsCancellation", "usesSpecialTaxRegimes", "usesServiceListItem", "specialTaxRegimesList", "nationalPortalTaxCalculationRegimeList", "nationalPortalTaxCalculationRegimeHelp", "municipalInscriptionHelp", "specialTaxRegimeHelp", "serviceListItemHelp", "digitalCertificatedHelp", "accessTokenHelp", "municipalServiceCodeHelp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FiscalInfoMunicipalOptionsGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in special_tax_regimes_list (list)
        _items = []
        if self.special_tax_regimes_list:
            for _item_special_tax_regimes_list in self.special_tax_regimes_list:
                if _item_special_tax_regimes_list:
                    _items.append(_item_special_tax_regimes_list.to_dict())
            _dict['specialTaxRegimesList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in national_portal_tax_calculation_regime_list (list)
        _items = []
        if self.national_portal_tax_calculation_regime_list:
            for _item_national_portal_tax_calculation_regime_list in self.national_portal_tax_calculation_regime_list:
                if _item_national_portal_tax_calculation_regime_list:
                    _items.append(_item_national_portal_tax_calculation_regime_list.to_dict())
            _dict['nationalPortalTaxCalculationRegimeList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FiscalInfoMunicipalOptionsGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authenticationType": obj.get("authenticationType"),
            "supportsCancellation": obj.get("supportsCancellation") if obj.get("supportsCancellation") is not None else True,
            "usesSpecialTaxRegimes": obj.get("usesSpecialTaxRegimes") if obj.get("usesSpecialTaxRegimes") is not None else True,
            "usesServiceListItem": obj.get("usesServiceListItem") if obj.get("usesServiceListItem") is not None else True,
            "specialTaxRegimesList": [FiscalInfoMunicipalOptionsSpecialTaxRegimesDTO.from_dict(_item) for _item in obj["specialTaxRegimesList"]] if obj.get("specialTaxRegimesList") is not None else None,
            "nationalPortalTaxCalculationRegimeList": [FiscalInfoMunicipalOptionsNationalPortalTaxCalculationRegimeDTO.from_dict(_item) for _item in obj["nationalPortalTaxCalculationRegimeList"]] if obj.get("nationalPortalTaxCalculationRegimeList") is not None else None,
            "nationalPortalTaxCalculationRegimeHelp": obj.get("nationalPortalTaxCalculationRegimeHelp"),
            "municipalInscriptionHelp": obj.get("municipalInscriptionHelp"),
            "specialTaxRegimeHelp": obj.get("specialTaxRegimeHelp"),
            "serviceListItemHelp": obj.get("serviceListItemHelp"),
            "digitalCertificatedHelp": obj.get("digitalCertificatedHelp"),
            "accessTokenHelp": obj.get("accessTokenHelp"),
            "municipalServiceCodeHelp": obj.get("municipalServiceCodeHelp")
        })
        return _obj


