# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InstallmentSaveRequestBillingType(str, Enum):
    """
    Forma de pagamento
    """

    """
    allowed enum values
    """
    UNDEFINED = 'UNDEFINED'
    BOLETO = 'BOLETO'
    CREDIT_CARD = 'CREDIT_CARD'
    PIX = 'PIX'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InstallmentSaveRequestBillingType from a JSON string"""
        return cls(json.loads(json_str))


