# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.installment_save_request_billing_type import InstallmentSaveRequestBillingType
from asaas.models.installment_split_request_dto import InstallmentSplitRequestDTO
from asaas.models.payment_discount_dto import PaymentDiscountDTO
from asaas.models.payment_fine_request_dto import PaymentFineRequestDTO
from asaas.models.payment_interest_request_dto import PaymentInterestRequestDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstallmentSaveRequestDTO(BaseModel):
    """
    InstallmentSaveRequestDTO
    """ # noqa: E501
    installment_count: StrictInt = Field(description="Número de parcelas", alias="installmentCount")
    customer: StrictStr = Field(description="Identificador único do cliente no Asaas")
    value: Union[StrictFloat, StrictInt] = Field(description="Valor de cada parcela")
    total_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor total do parcelamento", alias="totalValue")
    billing_type: InstallmentSaveRequestBillingType = Field(alias="billingType")
    due_date: date = Field(description="Data de vencimento da primeira parcela", alias="dueDate")
    description: Optional[StrictStr] = Field(default=None, description="Descrição do parcelamento (máx. 500 caracteres)")
    postal_service: Optional[StrictBool] = Field(default=None, description="Define se a cobrança será enviada via Correios", alias="postalService")
    days_after_due_date_to_registration_cancellation: Optional[StrictInt] = Field(default=None, description="Dias após o vencimento para cancelamento do registro (somente para boleto bancário)", alias="daysAfterDueDateToRegistrationCancellation")
    payment_external_reference: Optional[StrictStr] = Field(default=None, description="Campo livre para busca", alias="paymentExternalReference")
    discount: Optional[PaymentDiscountDTO] = None
    interest: Optional[PaymentInterestRequestDTO] = None
    fine: Optional[PaymentFineRequestDTO] = None
    splits: Optional[List[InstallmentSplitRequestDTO]] = Field(default=None, description="Configurações do split")
    __properties: ClassVar[List[str]] = ["installmentCount", "customer", "value", "totalValue", "billingType", "dueDate", "description", "postalService", "daysAfterDueDateToRegistrationCancellation", "paymentExternalReference", "discount", "interest", "fine", "splits"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstallmentSaveRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of discount
        if self.discount:
            _dict['discount'] = self.discount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interest
        if self.interest:
            _dict['interest'] = self.interest.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fine
        if self.fine:
            _dict['fine'] = self.fine.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in splits (list)
        _items = []
        if self.splits:
            for _item_splits in self.splits:
                if _item_splits:
                    _items.append(_item_splits.to_dict())
            _dict['splits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstallmentSaveRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "installmentCount": obj.get("installmentCount"),
            "customer": obj.get("customer"),
            "value": obj.get("value"),
            "totalValue": obj.get("totalValue"),
            "billingType": obj.get("billingType"),
            "dueDate": obj.get("dueDate"),
            "description": obj.get("description"),
            "postalService": obj.get("postalService"),
            "daysAfterDueDateToRegistrationCancellation": obj.get("daysAfterDueDateToRegistrationCancellation"),
            "paymentExternalReference": obj.get("paymentExternalReference"),
            "discount": PaymentDiscountDTO.from_dict(obj["discount"]) if obj.get("discount") is not None else None,
            "interest": PaymentInterestRequestDTO.from_dict(obj["interest"]) if obj.get("interest") is not None else None,
            "fine": PaymentFineRequestDTO.from_dict(obj["fine"]) if obj.get("fine") is not None else None,
            "splits": [InstallmentSplitRequestDTO.from_dict(_item) for _item in obj["splits"]] if obj.get("splits") is not None else None
        })
        return _obj


