# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvoiceTaxesRequestDTO(BaseModel):
    """
    Impostos da nota fiscal
    """ # noqa: E501
    nbs_code: Optional[StrictStr] = Field(default=None, description="Código NBS (Nomenclatura Brasileira de Serviços)", alias="nbsCode")
    tax_situation_code: Optional[StrictStr] = Field(default=None, description="Código de situação tributária", alias="taxSituationCode")
    tax_classification_code: Optional[StrictStr] = Field(default=None, description="Código de classificação tributária", alias="taxClassificationCode")
    operation_indicator_code: Optional[StrictStr] = Field(default=None, description="Código do indicador de operação", alias="operationIndicatorCode")
    retain_iss: StrictBool = Field(description="Tomador da nota fiscal deve reter ISS ou não", alias="retainIss")
    iss: Union[StrictFloat, StrictInt] = Field(description="Alíquota ISS")
    pis_cofins_retention_type: Optional[StrictStr] = Field(default=None, description="Tipo de retenção do PIS/COFINS", alias="pisCofinsRetentionType")
    pis_cofins_tax_status: Optional[StrictStr] = Field(default=None, description="Situação tributária do PIS/COFINS", alias="pisCofinsTaxStatus")
    pis: Union[StrictFloat, StrictInt] = Field(description="Alíquota PIS")
    cofins: Union[StrictFloat, StrictInt] = Field(description="Alíquota COFINS")
    csll: Union[StrictFloat, StrictInt] = Field(description="Alíquota CSLL")
    inss: Union[StrictFloat, StrictInt] = Field(description="Alíquota INSS")
    ir: Union[StrictFloat, StrictInt] = Field(description="Alíquota IR")
    __properties: ClassVar[List[str]] = ["nbsCode", "taxSituationCode", "taxClassificationCode", "operationIndicatorCode", "retainIss", "iss", "pisCofinsRetentionType", "pisCofinsTaxStatus", "pis", "cofins", "csll", "inss", "ir"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceTaxesRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceTaxesRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nbsCode": obj.get("nbsCode"),
            "taxSituationCode": obj.get("taxSituationCode"),
            "taxClassificationCode": obj.get("taxClassificationCode"),
            "operationIndicatorCode": obj.get("operationIndicatorCode"),
            "retainIss": obj.get("retainIss"),
            "iss": obj.get("iss"),
            "pisCofinsRetentionType": obj.get("pisCofinsRetentionType"),
            "pisCofinsTaxStatus": obj.get("pisCofinsTaxStatus"),
            "pis": obj.get("pis"),
            "cofins": obj.get("cofins"),
            "csll": obj.get("csll"),
            "inss": obj.get("inss"),
            "ir": obj.get("ir")
        })
        return _obj


