# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from asaas.models.my_account_get_account_fees_anticipation_dto import MyAccountGetAccountFeesAnticipationDTO
from asaas.models.my_account_get_account_fees_credit_bureau_report_dto import MyAccountGetAccountFeesCreditBureauReportDTO
from asaas.models.my_account_get_account_fees_invoice_dto import MyAccountGetAccountFeesInvoiceDTO
from asaas.models.my_account_get_account_fees_notification_dto import MyAccountGetAccountFeesNotificationDTO
from asaas.models.my_account_get_account_fees_payment_dto import MyAccountGetAccountFeesPaymentDTO
from asaas.models.my_account_get_account_fees_payment_dunning_dto import MyAccountGetAccountFeesPaymentDunningDTO
from asaas.models.my_account_get_account_fees_transfer_dto import MyAccountGetAccountFeesTransferDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MyAccountGetAccountFeesResponseDTO(BaseModel):
    """
    MyAccountGetAccountFeesResponseDTO
    """ # noqa: E501
    payment: Optional[MyAccountGetAccountFeesPaymentDTO] = None
    transfer: Optional[MyAccountGetAccountFeesTransferDTO] = None
    notification: Optional[MyAccountGetAccountFeesNotificationDTO] = None
    credit_bureau_report: Optional[MyAccountGetAccountFeesCreditBureauReportDTO] = Field(default=None, alias="creditBureauReport")
    payment_dunning: Optional[MyAccountGetAccountFeesPaymentDunningDTO] = Field(default=None, alias="paymentDunning")
    invoice: Optional[MyAccountGetAccountFeesInvoiceDTO] = None
    anticipation: Optional[MyAccountGetAccountFeesAnticipationDTO] = None
    __properties: ClassVar[List[str]] = ["payment", "transfer", "notification", "creditBureauReport", "paymentDunning", "invoice", "anticipation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MyAccountGetAccountFeesResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of payment
        if self.payment:
            _dict['payment'] = self.payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transfer
        if self.transfer:
            _dict['transfer'] = self.transfer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notification
        if self.notification:
            _dict['notification'] = self.notification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credit_bureau_report
        if self.credit_bureau_report:
            _dict['creditBureauReport'] = self.credit_bureau_report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_dunning
        if self.payment_dunning:
            _dict['paymentDunning'] = self.payment_dunning.to_dict()
        # override the default output from pydantic by calling `to_dict()` of invoice
        if self.invoice:
            _dict['invoice'] = self.invoice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of anticipation
        if self.anticipation:
            _dict['anticipation'] = self.anticipation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MyAccountGetAccountFeesResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payment": MyAccountGetAccountFeesPaymentDTO.from_dict(obj["payment"]) if obj.get("payment") is not None else None,
            "transfer": MyAccountGetAccountFeesTransferDTO.from_dict(obj["transfer"]) if obj.get("transfer") is not None else None,
            "notification": MyAccountGetAccountFeesNotificationDTO.from_dict(obj["notification"]) if obj.get("notification") is not None else None,
            "creditBureauReport": MyAccountGetAccountFeesCreditBureauReportDTO.from_dict(obj["creditBureauReport"]) if obj.get("creditBureauReport") is not None else None,
            "paymentDunning": MyAccountGetAccountFeesPaymentDunningDTO.from_dict(obj["paymentDunning"]) if obj.get("paymentDunning") is not None else None,
            "invoice": MyAccountGetAccountFeesInvoiceDTO.from_dict(obj["invoice"]) if obj.get("invoice") is not None else None,
            "anticipation": MyAccountGetAccountFeesAnticipationDTO.from_dict(obj["anticipation"]) if obj.get("anticipation") is not None else None
        })
        return _obj


