# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.payment_callback_request_dto import PaymentCallbackRequestDTO
from asaas.models.payment_link_update_request_billing_type import PaymentLinkUpdateRequestBillingType
from asaas.models.payment_link_update_request_charge_type import PaymentLinkUpdateRequestChargeType
from asaas.models.payment_link_update_request_cycle import PaymentLinkUpdateRequestCycle
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentLinkUpdateRequestDTO(BaseModel):
    """
    PaymentLinkUpdateRequestDTO
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Nome do link de pagamentos")
    description: Optional[StrictStr] = Field(default=None, description="Descrição do link de pagamentos")
    end_date: Optional[StrictStr] = Field(default=None, description="Data de encerramento", alias="endDate")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor do link de pagamentos, caso não informado o pagador poderá informar o quanto deseja pagar")
    active: Optional[StrictBool] = Field(default=None, description="Determina se o link de pagamentos está ativo")
    billing_type: Optional[PaymentLinkUpdateRequestBillingType] = Field(default=None, alias="billingType")
    charge_type: Optional[PaymentLinkUpdateRequestChargeType] = Field(default=None, alias="chargeType")
    due_date_limit_days: Optional[StrictInt] = Field(default=None, description="Quantidade de dias úteis que o seu cliente poderá pagar após o boleto ser gerado (Para forma de pagamento como Boleto)", alias="dueDateLimitDays")
    subscription_cycle: Optional[PaymentLinkUpdateRequestCycle] = Field(default=None, alias="subscriptionCycle")
    max_installment_count: Optional[StrictInt] = Field(default=1, description="Quantidade máxima de parcelas que seu cliente poderá parcelar o valor do link de pagamentos caso a forma de cobrança selecionado seja Parcelamento. Caso não informado o valor padrão será de 1 parcela", alias="maxInstallmentCount")
    external_reference: Optional[StrictStr] = Field(default=None, description="Campo livre para busca", alias="externalReference")
    notification_enabled: Optional[StrictBool] = Field(default=True, description="Define se os clientes cadastrados pelo link de pagamentos terão as notificações habilitadas. Caso não seja informado o valor padrão será true", alias="notificationEnabled")
    callback: Optional[PaymentCallbackRequestDTO] = None
    __properties: ClassVar[List[str]] = ["name", "description", "endDate", "value", "active", "billingType", "chargeType", "dueDateLimitDays", "subscriptionCycle", "maxInstallmentCount", "externalReference", "notificationEnabled", "callback"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentLinkUpdateRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of callback
        if self.callback:
            _dict['callback'] = self.callback.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentLinkUpdateRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "endDate": obj.get("endDate"),
            "value": obj.get("value"),
            "active": obj.get("active"),
            "billingType": obj.get("billingType"),
            "chargeType": obj.get("chargeType"),
            "dueDateLimitDays": obj.get("dueDateLimitDays"),
            "subscriptionCycle": obj.get("subscriptionCycle"),
            "maxInstallmentCount": obj.get("maxInstallmentCount") if obj.get("maxInstallmentCount") is not None else 1,
            "externalReference": obj.get("externalReference"),
            "notificationEnabled": obj.get("notificationEnabled") if obj.get("notificationEnabled") is not None else True,
            "callback": PaymentCallbackRequestDTO.from_dict(obj["callback"]) if obj.get("callback") is not None else None
        })
        return _obj


