# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.pix_receiver_automatic_recurring_authorization_get_response_pix_automatic_recurring_frequency import PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringFrequency
from asaas.models.pix_receiver_automatic_recurring_authorization_get_response_pix_automatic_recurring_origin_type import PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType
from asaas.models.pix_receiver_automatic_recurring_authorization_get_response_pix_receiver_automatic_recurring_authorization_status import PixReceiverAutomaticRecurringAuthorizationGetResponsePixReceiverAutomaticRecurringAuthorizationStatus
from asaas.models.pix_receiver_automatic_recurring_authorization_immediate_qr_code_response_dto import PixReceiverAutomaticRecurringAuthorizationImmediateQrCodeResponseDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PixReceiverAutomaticRecurringAuthorizationGetResponseDTO(BaseModel):
    """
    PixReceiverAutomaticRecurringAuthorizationGetResponseDTO
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Identificador único da autorização de Pix Automático no Asaas")
    min_limit_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Se o usuário pagador atribuir um valor máximo para os pagamentos daquela autorização, ele não poderá ser inferior ao piso definido pelo usuário recebedor. Não pode ser preenchido nas autorizações de valor fixo, ou seja, com campo valor preenchido", alias="minLimitValue")
    cancellation_date: Optional[date] = Field(default=None, description="Data de cancelamento da autorização", alias="cancellationDate")
    cancellation_reason: Optional[StrictStr] = Field(default=None, description="Motivo do cancelamento", alias="cancellationReason")
    contract_id: Optional[StrictStr] = Field(default=None, description="Número, identificador, ou código que representa o objeto da autorização", alias="contractId")
    customer_id: Optional[StrictStr] = Field(default=None, description="Identificador único do cliente", alias="customerId")
    description: Optional[StrictStr] = Field(default=None, description="Descrição da autorização")
    finish_date: Optional[date] = Field(default=None, description="Fim da vigência da autorização", alias="finishDate")
    frequency: Optional[PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringFrequency] = None
    end_to_end_identifier: Optional[StrictStr] = Field(default=None, description="Identificador fim a fim", alias="endToEndIdentifier")
    start_date: Optional[date] = Field(default=None, description="Inicio da vigência da autorização e dos pagamentos", alias="startDate")
    status: Optional[PixReceiverAutomaticRecurringAuthorizationGetResponsePixReceiverAutomaticRecurringAuthorizationStatus] = None
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor fixo para as cobranças periódicas")
    payload: Optional[StrictStr] = Field(default=None, description="Payload do QR Code")
    encoded_image: Optional[StrictStr] = Field(default=None, description="Imagem do QR Code em base64", alias="encodedImage")
    immediate_qr_code: Optional[PixReceiverAutomaticRecurringAuthorizationImmediateQrCodeResponseDTO] = Field(default=None, alias="immediateQrCode")
    origin_type: Optional[PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType] = Field(default=None, alias="originType")
    subscription_id: Optional[StrictStr] = Field(default=None, description="Identificador único da assinatura vinculada", alias="subscriptionId")
    __properties: ClassVar[List[str]] = ["id", "minLimitValue", "cancellationDate", "cancellationReason", "contractId", "customerId", "description", "finishDate", "frequency", "endToEndIdentifier", "startDate", "status", "value", "payload", "encodedImage", "immediateQrCode", "originType", "subscriptionId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PixReceiverAutomaticRecurringAuthorizationGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of immediate_qr_code
        if self.immediate_qr_code:
            _dict['immediateQrCode'] = self.immediate_qr_code.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PixReceiverAutomaticRecurringAuthorizationGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "minLimitValue": obj.get("minLimitValue"),
            "cancellationDate": obj.get("cancellationDate"),
            "cancellationReason": obj.get("cancellationReason"),
            "contractId": obj.get("contractId"),
            "customerId": obj.get("customerId"),
            "description": obj.get("description"),
            "finishDate": obj.get("finishDate"),
            "frequency": obj.get("frequency"),
            "endToEndIdentifier": obj.get("endToEndIdentifier"),
            "startDate": obj.get("startDate"),
            "status": obj.get("status"),
            "value": obj.get("value"),
            "payload": obj.get("payload"),
            "encodedImage": obj.get("encodedImage"),
            "immediateQrCode": PixReceiverAutomaticRecurringAuthorizationImmediateQrCodeResponseDTO.from_dict(obj["immediateQrCode"]) if obj.get("immediateQrCode") is not None else None,
            "originType": obj.get("originType"),
            "subscriptionId": obj.get("subscriptionId")
        })
        return _obj


