# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.pix_recurring_transaction_external_account_dto import PixRecurringTransactionExternalAccountDTO
from asaas.models.pix_recurring_transaction_get_item_response_pix_recurring_transaction_item_status import PixRecurringTransactionGetItemResponsePixRecurringTransactionItemStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PixRecurringTransactionGetItemResponseDTO(BaseModel):
    """
    PixRecurringTransactionGetItemResponseDTO
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Identificador único do item de uma recorrência no Asaas")
    status: Optional[PixRecurringTransactionGetItemResponsePixRecurringTransactionItemStatus] = None
    scheduled_date: Optional[date] = Field(default=None, description="Data de agendamento do item de uma recorrência", alias="scheduledDate")
    can_be_cancelled: Optional[StrictBool] = Field(default=None, description="Indica se o item de uma recorrência pode ser cancelado", alias="canBeCancelled")
    recurrence_number: Optional[StrictInt] = Field(default=None, description="Número da recorrência", alias="recurrenceNumber")
    quantity: Optional[StrictInt] = Field(default=None, description="Quantidade de repetições")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor da recorrência")
    refusal_reason_description: Optional[StrictStr] = Field(default=None, description="Motivo pelo qual o item de uma recorrência foi recusado", alias="refusalReasonDescription")
    external_account: Optional[PixRecurringTransactionExternalAccountDTO] = Field(default=None, alias="externalAccount")
    __properties: ClassVar[List[str]] = ["id", "status", "scheduledDate", "canBeCancelled", "recurrenceNumber", "quantity", "value", "refusalReasonDescription", "externalAccount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PixRecurringTransactionGetItemResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_account
        if self.external_account:
            _dict['externalAccount'] = self.external_account.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PixRecurringTransactionGetItemResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "scheduledDate": obj.get("scheduledDate"),
            "canBeCancelled": obj.get("canBeCancelled"),
            "recurrenceNumber": obj.get("recurrenceNumber"),
            "quantity": obj.get("quantity"),
            "value": obj.get("value"),
            "refusalReasonDescription": obj.get("refusalReasonDescription"),
            "externalAccount": PixRecurringTransactionExternalAccountDTO.from_dict(obj["externalAccount"]) if obj.get("externalAccount") is not None else None
        })
        return _obj


