# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.pix_original_transaction_response_dto import PixOriginalTransactionResponseDTO
from asaas.models.pix_transaction_external_account_response_dto import PixTransactionExternalAccountResponseDTO
from asaas.models.pix_transaction_get_response_pix_address_key_type import PixTransactionGetResponsePixAddressKeyType
from asaas.models.pix_transaction_get_response_pix_transaction_cash_value_finality import PixTransactionGetResponsePixTransactionCashValueFinality
from asaas.models.pix_transaction_get_response_pix_transaction_origin_type import PixTransactionGetResponsePixTransactionOriginType
from asaas.models.pix_transaction_get_response_pix_transaction_status import PixTransactionGetResponsePixTransactionStatus
from asaas.models.pix_transaction_get_response_pix_transaction_type import PixTransactionGetResponsePixTransactionType
from asaas.models.pix_transaction_qr_code_response_dto import PixTransactionQrCodeResponseDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PixTransactionGetResponseDTO(BaseModel):
    """
    PixTransactionGetResponseDTO
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Identificador único da transação Pix no Asaas")
    end_to_end_identifier: Optional[StrictStr] = Field(default=None, description="Identificador da transação Pix no Banco Central", alias="endToEndIdentifier")
    finality: Optional[PixTransactionGetResponsePixTransactionCashValueFinality] = None
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor da transação ou de um Saque")
    change_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor do troco", alias="changeValue")
    refunded_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor estornado", alias="refundedValue")
    effective_date: Optional[datetime] = Field(default=None, description="Data da transação", alias="effectiveDate")
    scheduled_date: Optional[date] = Field(default=None, description="Data do agendamento", alias="scheduledDate")
    status: Optional[PixTransactionGetResponsePixTransactionStatus] = None
    type: Optional[PixTransactionGetResponsePixTransactionType] = None
    origin_type: Optional[PixTransactionGetResponsePixTransactionOriginType] = Field(default=None, alias="originType")
    conciliation_identifier: Optional[StrictStr] = Field(default=None, description="Identificador do QrCode vinculado a transação", alias="conciliationIdentifier")
    description: Optional[StrictStr] = Field(default=None, description="Descrição sobre a transação")
    transaction_receipt_url: Optional[StrictStr] = Field(default=None, description="Comprovante de transação, estará disponível após a transação ser confirmada.", alias="transactionReceiptUrl")
    refusal_reason: Optional[StrictStr] = Field(default=None, description="Motivo pelo qual a transação foi recusada", alias="refusalReason")
    can_be_canceled: Optional[StrictBool] = Field(default=None, description="Indica se a transação pode ser cancelada", alias="canBeCanceled")
    original_transaction: Optional[PixOriginalTransactionResponseDTO] = Field(default=None, alias="originalTransaction")
    external_account: Optional[PixTransactionExternalAccountResponseDTO] = Field(default=None, alias="externalAccount")
    qr_code: Optional[PixTransactionQrCodeResponseDTO] = Field(default=None, alias="qrCode")
    payment: Optional[StrictStr] = Field(default=None, description="Identificador único da cobrança")
    can_be_refunded: Optional[StrictBool] = Field(default=None, description="Indica se a transação pode ser estornada", alias="canBeRefunded")
    refund_disabled_reason: Optional[StrictStr] = Field(default=None, description="Motivo pelo qual o estorno foi desabilitado", alias="refundDisabledReason")
    charged_fee_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Taxa de débito ou crédito referente a transação", alias="chargedFeeValue")
    date_created: Optional[datetime] = Field(default=None, description="Data de criação da transação", alias="dateCreated")
    address_key: Optional[StrictStr] = Field(default=None, description="Chave Pix quando a transação é um crédito", alias="addressKey")
    address_key_type: Optional[PixTransactionGetResponsePixAddressKeyType] = Field(default=None, alias="addressKeyType")
    transfer_id: Optional[StrictStr] = Field(default=None, description="Identificador da transferência", alias="transferId")
    external_reference: Optional[StrictStr] = Field(default=None, description="Campo livre para busca", alias="externalReference")
    __properties: ClassVar[List[str]] = ["id", "endToEndIdentifier", "finality", "value", "changeValue", "refundedValue", "effectiveDate", "scheduledDate", "status", "type", "originType", "conciliationIdentifier", "description", "transactionReceiptUrl", "refusalReason", "canBeCanceled", "originalTransaction", "externalAccount", "qrCode", "payment", "canBeRefunded", "refundDisabledReason", "chargedFeeValue", "dateCreated", "addressKey", "addressKeyType", "transferId", "externalReference"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PixTransactionGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of original_transaction
        if self.original_transaction:
            _dict['originalTransaction'] = self.original_transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of external_account
        if self.external_account:
            _dict['externalAccount'] = self.external_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of qr_code
        if self.qr_code:
            _dict['qrCode'] = self.qr_code.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PixTransactionGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "endToEndIdentifier": obj.get("endToEndIdentifier"),
            "finality": obj.get("finality"),
            "value": obj.get("value"),
            "changeValue": obj.get("changeValue"),
            "refundedValue": obj.get("refundedValue"),
            "effectiveDate": obj.get("effectiveDate"),
            "scheduledDate": obj.get("scheduledDate"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "originType": obj.get("originType"),
            "conciliationIdentifier": obj.get("conciliationIdentifier"),
            "description": obj.get("description"),
            "transactionReceiptUrl": obj.get("transactionReceiptUrl"),
            "refusalReason": obj.get("refusalReason"),
            "canBeCanceled": obj.get("canBeCanceled"),
            "originalTransaction": PixOriginalTransactionResponseDTO.from_dict(obj["originalTransaction"]) if obj.get("originalTransaction") is not None else None,
            "externalAccount": PixTransactionExternalAccountResponseDTO.from_dict(obj["externalAccount"]) if obj.get("externalAccount") is not None else None,
            "qrCode": PixTransactionQrCodeResponseDTO.from_dict(obj["qrCode"]) if obj.get("qrCode") is not None else None,
            "payment": obj.get("payment"),
            "canBeRefunded": obj.get("canBeRefunded"),
            "refundDisabledReason": obj.get("refundDisabledReason"),
            "chargedFeeValue": obj.get("chargedFeeValue"),
            "dateCreated": obj.get("dateCreated"),
            "addressKey": obj.get("addressKey"),
            "addressKeyType": obj.get("addressKeyType"),
            "transferId": obj.get("transferId"),
            "externalReference": obj.get("externalReference")
        })
        return _obj


