# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from asaas.models.pix_address_key_get_response_pix_address_key_status import PixAddressKeyGetResponsePixAddressKeyStatus
from asaas.models.pix_address_key_get_response_pix_address_key_type import PixAddressKeyGetResponsePixAddressKeyType
from asaas.models.pix_address_key_qr_code_get_response_dto import PixAddressKeyQrCodeGetResponseDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PixAddressKeyGetResponseDTO(BaseModel):
    """
    PixAddressKeyGetResponseDTO
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Identificador único da chave Pix no Asaas")
    key: Optional[StrictStr] = Field(default=None, description="Valor da chave")
    type: Optional[PixAddressKeyGetResponsePixAddressKeyType] = None
    status: Optional[PixAddressKeyGetResponsePixAddressKeyStatus] = None
    date_created: Optional[datetime] = Field(default=None, description="Data de criação da chave", alias="dateCreated")
    can_be_deleted: Optional[StrictBool] = Field(default=None, description="Determina se a chave pode ser deletada", alias="canBeDeleted")
    cannot_be_deleted_reason: Optional[StrictStr] = Field(default=None, description="Motivo de não poder ser removida", alias="cannotBeDeletedReason")
    qr_code: Optional[PixAddressKeyQrCodeGetResponseDTO] = Field(default=None, alias="qrCode")
    __properties: ClassVar[List[str]] = ["id", "key", "type", "status", "dateCreated", "canBeDeleted", "cannotBeDeletedReason", "qrCode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PixAddressKeyGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of qr_code
        if self.qr_code:
            _dict['qrCode'] = self.qr_code.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PixAddressKeyGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "key": obj.get("key"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "dateCreated": obj.get("dateCreated"),
            "canBeDeleted": obj.get("canBeDeleted"),
            "cannotBeDeletedReason": obj.get("cannotBeDeletedReason"),
            "qrCode": PixAddressKeyQrCodeGetResponseDTO.from_dict(obj["qrCode"]) if obj.get("qrCode") is not None else None
        })
        return _obj


