# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.payment_discount_dto import PaymentDiscountDTO
from asaas.models.payment_fine_response_dto import PaymentFineResponseDTO
from asaas.models.payment_interest_response_dto import PaymentInterestResponseDTO
from asaas.models.subscription_get_response_billing_type import SubscriptionGetResponseBillingType
from asaas.models.subscription_get_response_cycle import SubscriptionGetResponseCycle
from asaas.models.subscription_get_response_subscription_status import SubscriptionGetResponseSubscriptionStatus
from asaas.models.subscription_split_response_dto import SubscriptionSplitResponseDTO
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionGetResponseDTO(BaseModel):
    """
    SubscriptionGetResponseDTO
    """ # noqa: E501
    object: Optional[StrictStr] = Field(default=None, description="Tipo do objeto")
    id: Optional[StrictStr] = Field(default=None, description="Identificador único da assinatura no Asaas")
    date_created: Optional[date] = Field(default=None, description="Data de criação da assinatura", alias="dateCreated")
    customer: Optional[StrictStr] = Field(default=None, description="Identificador único do cliente")
    payment_link: Optional[StrictStr] = Field(default=None, description="Identificador único do link de pagamentos ao qual a assinatura pertence", alias="paymentLink")
    billing_type: Optional[SubscriptionGetResponseBillingType] = Field(default=None, alias="billingType")
    cycle: Optional[SubscriptionGetResponseCycle] = None
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor da assinatura")
    next_due_date: Optional[date] = Field(default=None, description="Vencimento do próximo pagamento a ser gerado", alias="nextDueDate")
    end_date: Optional[date] = Field(default=None, description="Data limite para vencimento das cobranças", alias="endDate")
    description: Optional[StrictStr] = Field(default=None, description="Descrição da assinatura")
    status: Optional[SubscriptionGetResponseSubscriptionStatus] = None
    discount: Optional[PaymentDiscountDTO] = None
    fine: Optional[PaymentFineResponseDTO] = None
    interest: Optional[PaymentInterestResponseDTO] = None
    deleted: Optional[StrictBool] = Field(default=None, description="Informa se a assinatura foi removida")
    max_payments: Optional[StrictInt] = Field(default=None, description="Número máximo de cobranças a serem geradas para esta assinatura", alias="maxPayments")
    external_reference: Optional[StrictStr] = Field(default=None, description="Identificador da assinatura no seu sistema", alias="externalReference")
    checkout_session: Optional[StrictStr] = Field(default=None, description="Identificador único do checkout", alias="checkoutSession")
    split: Optional[List[SubscriptionSplitResponseDTO]] = Field(default=None, description="Informações de split")
    __properties: ClassVar[List[str]] = ["object", "id", "dateCreated", "customer", "paymentLink", "billingType", "cycle", "value", "nextDueDate", "endDate", "description", "status", "discount", "fine", "interest", "deleted", "maxPayments", "externalReference", "checkoutSession", "split"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of discount
        if self.discount:
            _dict['discount'] = self.discount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fine
        if self.fine:
            _dict['fine'] = self.fine.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interest
        if self.interest:
            _dict['interest'] = self.interest.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in split (list)
        _items = []
        if self.split:
            for _item_split in self.split:
                if _item_split:
                    _items.append(_item_split.to_dict())
            _dict['split'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "dateCreated": obj.get("dateCreated"),
            "customer": obj.get("customer"),
            "paymentLink": obj.get("paymentLink"),
            "billingType": obj.get("billingType"),
            "cycle": obj.get("cycle"),
            "value": obj.get("value"),
            "nextDueDate": obj.get("nextDueDate"),
            "endDate": obj.get("endDate"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "discount": PaymentDiscountDTO.from_dict(obj["discount"]) if obj.get("discount") is not None else None,
            "fine": PaymentFineResponseDTO.from_dict(obj["fine"]) if obj.get("fine") is not None else None,
            "interest": PaymentInterestResponseDTO.from_dict(obj["interest"]) if obj.get("interest") is not None else None,
            "deleted": obj.get("deleted"),
            "maxPayments": obj.get("maxPayments"),
            "externalReference": obj.get("externalReference"),
            "checkoutSession": obj.get("checkoutSession"),
            "split": [SubscriptionSplitResponseDTO.from_dict(_item) for _item in obj["split"]] if obj.get("split") is not None else None
        })
        return _obj


