# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from asaas.models.subscription_split_response_subscription_split_disabled_reason import SubscriptionSplitResponseSubscriptionSplitDisabledReason
from asaas.models.subscription_split_response_subscription_split_status import SubscriptionSplitResponseSubscriptionSplitStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionSplitResponseDTO(BaseModel):
    """
    Informações de split
    """ # noqa: E501
    wallet_id: Optional[StrictStr] = Field(default=None, description="Identificador da carteira Asaas que será transferido", alias="walletId")
    fixed_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor fixo a ser transferido para a conta quando a cobrança for recebida", alias="fixedValue")
    percentual_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentual sobre o valor líquido da cobrança a ser transferido quando for recebida", alias="percentualValue")
    external_reference: Optional[StrictStr] = Field(default=None, description="Identificador do split no seu sistema", alias="externalReference")
    description: Optional[StrictStr] = Field(default=None, description="Descrição do split")
    status: Optional[SubscriptionSplitResponseSubscriptionSplitStatus] = None
    disabled_reason: Optional[SubscriptionSplitResponseSubscriptionSplitDisabledReason] = Field(default=None, alias="disabledReason")
    __properties: ClassVar[List[str]] = ["walletId", "fixedValue", "percentualValue", "externalReference", "description", "status", "disabledReason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionSplitResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionSplitResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "walletId": obj.get("walletId"),
            "fixedValue": obj.get("fixedValue"),
            "percentualValue": obj.get("percentualValue"),
            "externalReference": obj.get("externalReference"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "disabledReason": obj.get("disabledReason")
        })
        return _obj


