# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from asaas.models.webhook_config_get_response_webhook_event import WebhookConfigGetResponseWebhookEvent
from asaas.models.webhook_config_get_response_webhook_send_type import WebhookConfigGetResponseWebhookSendType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WebhookConfigGetResponseDTO(BaseModel):
    """
    WebhookConfigGetResponseDTO
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Identificador único do Webhook")
    name: Optional[StrictStr] = Field(default=None, description="Nome do Webhook")
    url: Optional[StrictStr] = Field(default=None, description="URL do Webhook")
    email: Optional[StrictStr] = Field(default=None, description="E-mail que receberá notificações sobre o Webhook")
    enabled: Optional[StrictBool] = Field(default=None, description="Indica se o Webhook está ativo")
    interrupted: Optional[StrictBool] = Field(default=None, description="Definir se a fila de sincronização está interrompida")
    api_version: Optional[StrictInt] = Field(default=None, description="Versão da API", alias="apiVersion")
    has_auth_token: Optional[StrictBool] = Field(default=None, description="Indica se existe um token de autenticação registrado para o webhook", alias="hasAuthToken")
    send_type: Optional[WebhookConfigGetResponseWebhookSendType] = Field(default=None, alias="sendType")
    penalized_requests_count: Optional[StrictInt] = Field(default=None, description="Quantidade de requests penalizados", alias="penalizedRequestsCount")
    events: Optional[List[WebhookConfigGetResponseWebhookEvent]] = Field(default=None, description="Lista de eventos enviados pelo Webhook")
    __properties: ClassVar[List[str]] = ["id", "name", "url", "email", "enabled", "interrupted", "apiVersion", "hasAuthToken", "sendType", "penalizedRequestsCount", "events"]

    @field_validator('events')
    def events_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set([]):
                raise ValueError("each list item must be one of ()")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookConfigGetResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookConfigGetResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "url": obj.get("url"),
            "email": obj.get("email"),
            "enabled": obj.get("enabled"),
            "interrupted": obj.get("interrupted"),
            "apiVersion": obj.get("apiVersion"),
            "hasAuthToken": obj.get("hasAuthToken"),
            "sendType": obj.get("sendType"),
            "penalizedRequestsCount": obj.get("penalizedRequestsCount"),
            "events": obj.get("events")
        })
        return _obj


