# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_receiver_automatic_recurring_authorization_get_response_pix_automatic_recurring_origin_type import PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType

class TestPixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType(unittest.TestCase):
    """PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType(self):
        """Test PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType"""
        # inst = PixReceiverAutomaticRecurringAuthorizationGetResponsePixAutomaticRecurringOriginType()

if __name__ == '__main__':
    unittest.main()
