# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_recurring_transaction_list_response_dto import PixRecurringTransactionListResponseDTO

class TestPixRecurringTransactionListResponseDTO(unittest.TestCase):
    """PixRecurringTransactionListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixRecurringTransactionListResponseDTO:
        """Test PixRecurringTransactionListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixRecurringTransactionListResponseDTO`
        """
        model = PixRecurringTransactionListResponseDTO()
        if include_optional:
            return PixRecurringTransactionListResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.pix_recurring_transaction_get_response_dto.PixRecurringTransactionGetResponseDTO(
                        id = '35363f6e-93e2-11ec-b9d9-96f4053b1bd4', 
                        status = 'PENDING', 
                        origin = 'PIX', 
                        value = 0.02, 
                        frequency = 'WEEKLY', 
                        quantity = 2, 
                        start_date = 'Tue Sep 17 21:00:00 BRT 2024', 
                        finish_date = 'Tue Sep 24 21:00:00 BRT 2024', 
                        can_be_cancelled = True, 
                        external_account = asaas.models.pix_recurring_transaction_external_account_dto.PixRecurringTransactionExternalAccountDTO(
                            name = 'John Doe', 
                            financial_institution_name = 'Banco exemplo S.A', 
                            cpf_cnpj = '***.456.789-**', 
                            pix_key = '***.456.789-**', ), )
                    ]
            )
        else:
            return PixRecurringTransactionListResponseDTO(
        )
        """

    def testPixRecurringTransactionListResponseDTO(self):
        """Test PixRecurringTransactionListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
