# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.api.extrato_api import ExtratoApi


class TestExtratoApi(unittest.TestCase):
    """ExtratoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExtratoApi()

    def tearDown(self) -> None:
        pass

    def test_recuperar_extrato(self) -> None:
        """Test case for recuperar_extrato

        Recuperar extrato
        """
        pass


if __name__ == '__main__':
    unittest.main()
