# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_automatic_recurring_payment_instruction_authorization_response_dto import PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO

class TestPixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO(unittest.TestCase):
    """PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO:
        """Test PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO`
        """
        model = PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO()
        if include_optional:
            return PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO(
                id = '35363f6e-93e2-11ec-b9d9-96f4053b1bd4',
                end_to_end_identifier = 'RR1234567820240115abcdefghijk',
                customer_id = 'cus_000005735721'
            )
        else:
            return PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO(
        )
        """

    def testPixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO(self):
        """Test PixAutomaticRecurringPaymentInstructionAuthorizationResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
