# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.my_account_get_account_fees_payment_dto import MyAccountGetAccountFeesPaymentDTO

class TestMyAccountGetAccountFeesPaymentDTO(unittest.TestCase):
    """MyAccountGetAccountFeesPaymentDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MyAccountGetAccountFeesPaymentDTO:
        """Test MyAccountGetAccountFeesPaymentDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MyAccountGetAccountFeesPaymentDTO`
        """
        model = MyAccountGetAccountFeesPaymentDTO()
        if include_optional:
            return MyAccountGetAccountFeesPaymentDTO(
                bank_slip = asaas.models.my_account_get_account_fees_payment_bank_slip_dto.MyAccountGetAccountFeesPaymentBankSlipDTO(
                    default_value = 6.96, 
                    discount_value = 3.99, 
                    expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    days_to_receive = 1, ),
                credit_card = asaas.models.my_account_get_account_fees_payment_credit_card_dto.MyAccountGetAccountFeesPaymentCreditCardDTO(
                    operation_value = 0.49, 
                    one_installment_percentage = 2.99, 
                    up_to_six_installments_percentage = 2.99, 
                    up_to_twelve_installments_percentage = 2.99, 
                    up_to_twenty_one_installments_percentage = 4.29, 
                    discount_one_installment_percentage = 1.99, 
                    discount_up_to_six_installments_percentage = 1.99, 
                    discount_up_to_twelve_installments_percentage = 1.99, 
                    discount_up_to_twenty_one_installments_percentage = 3.29, 
                    discount_expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    days_to_receive = 32, ),
                debit_card = asaas.models.my_account_get_account_fees_payment_debit_card_dto.MyAccountGetAccountFeesPaymentDebitCardDTO(
                    operation_value = 0.35, 
                    default_percentage = 1.89, 
                    days_to_receive = 3, ),
                pix = asaas.models.my_account_get_account_fees_payment_pix_dto.MyAccountGetAccountFeesPaymentPixDTO(
                    fixed_fee_value = 1.337, 
                    fixed_fee_value_with_discount = 1.337, 
                    percentage_fee = 0.99, 
                    minimum_fee_value = 0.29, 
                    maximum_fee_value = 1.99, 
                    discount_expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    monthly_credits_without_fee = 30, 
                    credits_received_of_current_month = 10, )
            )
        else:
            return MyAccountGetAccountFeesPaymentDTO(
        )
        """

    def testMyAccountGetAccountFeesPaymentDTO(self):
        """Test MyAccountGetAccountFeesPaymentDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
