# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_split_list_paid_request_payment_split_status import PaymentSplitListPaidRequestPaymentSplitStatus

class TestPaymentSplitListPaidRequestPaymentSplitStatus(unittest.TestCase):
    """PaymentSplitListPaidRequestPaymentSplitStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentSplitListPaidRequestPaymentSplitStatus(self):
        """Test PaymentSplitListPaidRequestPaymentSplitStatus"""
        # inst = PaymentSplitListPaidRequestPaymentSplitStatus()

if __name__ == '__main__':
    unittest.main()
