# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_qr_code_decode_receiver_dto import PixQrCodeDecodeReceiverDTO

class TestPixQrCodeDecodeReceiverDTO(unittest.TestCase):
    """PixQrCodeDecodeReceiverDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixQrCodeDecodeReceiverDTO:
        """Test PixQrCodeDecodeReceiverDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixQrCodeDecodeReceiverDTO`
        """
        model = PixQrCodeDecodeReceiverDTO()
        if include_optional:
            return PixQrCodeDecodeReceiverDTO(
                ispb = '',
                ispb_name = '',
                name = '',
                trading_name = '',
                cpf_cnpj = '',
                person_type = 'JURIDICA',
                account_type = 'CHECKING_ACCOUNT'
            )
        else:
            return PixQrCodeDecodeReceiverDTO(
        )
        """

    def testPixQrCodeDecodeReceiverDTO(self):
        """Test PixQrCodeDecodeReceiverDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
