# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_receiver_automatic_recurring_authorization_save_request_dto import PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO

class TestPixReceiverAutomaticRecurringAuthorizationSaveRequestDTO(unittest.TestCase):
    """PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO:
        """Test PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO`
        """
        model = PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO()
        if include_optional:
            return PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO(
                frequency = 'MONTHLY',
                contract_id = 'CONTRACT-123',
                start_date = 'Sun Dec 31 21:00:00 BRT 2023',
                finish_date = 'Mon Dec 30 21:00:00 BRT 2024',
                value = 100,
                description = 'Serviços de Streaming de Música e Filmes',
                customer_id = 'cus_000005735721',
                immediate_qr_code = asaas.models.pix_receiver_automatic_recurring_authorization_immediate_qr_code_request_dto.PixReceiverAutomaticRecurringAuthorizationImmediateQrCodeRequestDTO(
                    pix_key = 'b6295ee1-f054-47d1-9e90-ee57b74f60d9', 
                    expiration_seconds = 3600, 
                    original_value = 100, 
                    description = 'Taxa de criação de conta', ),
                min_limit_value = 50
            )
        else:
            return PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO(
                frequency = 'MONTHLY',
                contract_id = 'CONTRACT-123',
                start_date = 'Sun Dec 31 21:00:00 BRT 2023',
                customer_id = 'cus_000005735721',
                immediate_qr_code = asaas.models.pix_receiver_automatic_recurring_authorization_immediate_qr_code_request_dto.PixReceiverAutomaticRecurringAuthorizationImmediateQrCodeRequestDTO(
                    pix_key = 'b6295ee1-f054-47d1-9e90-ee57b74f60d9', 
                    expiration_seconds = 3600, 
                    original_value = 100, 
                    description = 'Taxa de criação de conta', ),
        )
        """

    def testPixReceiverAutomaticRecurringAuthorizationSaveRequestDTO(self):
        """Test PixReceiverAutomaticRecurringAuthorizationSaveRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
