# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_address_key_qr_code_get_response_dto import PixAddressKeyQrCodeGetResponseDTO

class TestPixAddressKeyQrCodeGetResponseDTO(unittest.TestCase):
    """PixAddressKeyQrCodeGetResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixAddressKeyQrCodeGetResponseDTO:
        """Test PixAddressKeyQrCodeGetResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixAddressKeyQrCodeGetResponseDTO`
        """
        model = PixAddressKeyQrCodeGetResponseDTO()
        if include_optional:
            return PixAddressKeyQrCodeGetResponseDTO(
                encoded_image = 'QRCODE IMAGE IN BASE64',
                payload = '00020126580014br.gov.bcb.pix0136a9fe43bc-164d-44d1-91c2-2f9b4d6956e95204000053039865802BR5925Joao da Silva6009Joinville62290525JOAOSILVA00000055ASA6304E62B'
            )
        else:
            return PixAddressKeyQrCodeGetResponseDTO(
        )
        """

    def testPixAddressKeyQrCodeGetResponseDTO(self):
        """Test PixAddressKeyQrCodeGetResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
