# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_bank_slip_refund_response_dto import PaymentBankSlipRefundResponseDTO

class TestPaymentBankSlipRefundResponseDTO(unittest.TestCase):
    """PaymentBankSlipRefundResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentBankSlipRefundResponseDTO:
        """Test PaymentBankSlipRefundResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentBankSlipRefundResponseDTO`
        """
        model = PaymentBankSlipRefundResponseDTO()
        if include_optional:
            return PaymentBankSlipRefundResponseDTO(
                request_url = 'https://sandbox.asaas.com/solicitar-estorno/37ij5mdxwo1234'
            )
        else:
            return PaymentBankSlipRefundResponseDTO(
        )
        """

    def testPaymentBankSlipRefundResponseDTO(self):
        """Test PaymentBankSlipRefundResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
