# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.mobile_phone_recharge_find_provider_response_values_dto import MobilePhoneRechargeFindProviderResponseValuesDTO

class TestMobilePhoneRechargeFindProviderResponseValuesDTO(unittest.TestCase):
    """MobilePhoneRechargeFindProviderResponseValuesDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MobilePhoneRechargeFindProviderResponseValuesDTO:
        """Test MobilePhoneRechargeFindProviderResponseValuesDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MobilePhoneRechargeFindProviderResponseValuesDTO`
        """
        model = MobilePhoneRechargeFindProviderResponseValuesDTO()
        if include_optional:
            return MobilePhoneRechargeFindProviderResponseValuesDTO(
                name = 'R$ 12,00',
                description = '',
                bonus = '0.0',
                min_value = 12,
                max_value = 12
            )
        else:
            return MobilePhoneRechargeFindProviderResponseValuesDTO(
        )
        """

    def testMobilePhoneRechargeFindProviderResponseValuesDTO(self):
        """Test MobilePhoneRechargeFindProviderResponseValuesDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
