# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.notification_list_response_dto import NotificationListResponseDTO

class TestNotificationListResponseDTO(unittest.TestCase):
    """NotificationListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationListResponseDTO:
        """Test NotificationListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationListResponseDTO`
        """
        model = NotificationListResponseDTO()
        if include_optional:
            return NotificationListResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.notification_get_response_dto.NotificationGetResponseDTO(
                        object = 'notification', 
                        id = 'not_wuGp97JeCr7G', 
                        customer = 'cus_000005401844', 
                        enabled = True, 
                        email_enabled_for_provider = True, 
                        sms_enabled_for_provider = True, 
                        email_enabled_for_customer = True, 
                        sms_enabled_for_customer = True, 
                        phone_call_enabled_for_customer = False, 
                        whatsapp_enabled_for_customer = False, 
                        event = 'PAYMENT_CREATED', 
                        schedule_offset = 1, 
                        deleted = True, )
                    ]
            )
        else:
            return NotificationListResponseDTO(
        )
        """

    def testNotificationListResponseDTO(self):
        """Test NotificationListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
