# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.account_info_save_request_person_type import AccountInfoSaveRequestPersonType

class TestAccountInfoSaveRequestPersonType(unittest.TestCase):
    """AccountInfoSaveRequestPersonType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountInfoSaveRequestPersonType(self):
        """Test AccountInfoSaveRequestPersonType"""
        # inst = AccountInfoSaveRequestPersonType()

if __name__ == '__main__':
    unittest.main()
