# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_dunning_list_partial_payments_response_data_dto import PaymentDunningListPartialPaymentsResponseDataDTO

class TestPaymentDunningListPartialPaymentsResponseDataDTO(unittest.TestCase):
    """PaymentDunningListPartialPaymentsResponseDataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDunningListPartialPaymentsResponseDataDTO:
        """Test PaymentDunningListPartialPaymentsResponseDataDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDunningListPartialPaymentsResponseDataDTO`
        """
        model = PaymentDunningListPartialPaymentsResponseDataDTO()
        if include_optional:
            return PaymentDunningListPartialPaymentsResponseDataDTO(
                value = 800,
                description = 'A quitação desta cobrança foi efetuada pelo cliente.',
                payment_date = '2020-02-10'
            )
        else:
            return PaymentDunningListPartialPaymentsResponseDataDTO(
        )
        """

    def testPaymentDunningListPartialPaymentsResponseDataDTO(self):
        """Test PaymentDunningListPartialPaymentsResponseDataDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
