# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_fine_response_dto import PaymentFineResponseDTO

class TestPaymentFineResponseDTO(unittest.TestCase):
    """PaymentFineResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentFineResponseDTO:
        """Test PaymentFineResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentFineResponseDTO`
        """
        model = PaymentFineResponseDTO()
        if include_optional:
            return PaymentFineResponseDTO(
                value = 1
            )
        else:
            return PaymentFineResponseDTO(
        )
        """

    def testPaymentFineResponseDTO(self):
        """Test PaymentFineResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
