# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_simulate_request_billing_type import PaymentSimulateRequestBillingType

class TestPaymentSimulateRequestBillingType(unittest.TestCase):
    """PaymentSimulateRequestBillingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentSimulateRequestBillingType(self):
        """Test PaymentSimulateRequestBillingType"""
        # inst = PaymentSimulateRequestBillingType()

if __name__ == '__main__':
    unittest.main()
