# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.checkout_session_items_dto import CheckoutSessionItemsDTO

class TestCheckoutSessionItemsDTO(unittest.TestCase):
    """CheckoutSessionItemsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionItemsDTO:
        """Test CheckoutSessionItemsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionItemsDTO`
        """
        model = CheckoutSessionItemsDTO()
        if include_optional:
            return CheckoutSessionItemsDTO(
                external_reference = '8ad5c46e-bfdf-4e23-b66d-0f81c1b3530c',
                description = 'Camisetas',
                image_base64 = 'IMAGE IN BASE64',
                name = 'Roupas',
                quantity = 2,
                value = 100
            )
        else:
            return CheckoutSessionItemsDTO(
                image_base64 = 'IMAGE IN BASE64',
                name = 'Roupas',
                quantity = 2,
                value = 100,
        )
        """

    def testCheckoutSessionItemsDTO(self):
        """Test CheckoutSessionItemsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
