# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.credit_card_tokenize_response_credit_card_brand import CreditCardTokenizeResponseCreditCardBrand

class TestCreditCardTokenizeResponseCreditCardBrand(unittest.TestCase):
    """CreditCardTokenizeResponseCreditCardBrand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreditCardTokenizeResponseCreditCardBrand(self):
        """Test CreditCardTokenizeResponseCreditCardBrand"""
        # inst = CreditCardTokenizeResponseCreditCardBrand()

if __name__ == '__main__':
    unittest.main()
