# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.transfer_bank_save_request_dto import TransferBankSaveRequestDTO

class TestTransferBankSaveRequestDTO(unittest.TestCase):
    """TransferBankSaveRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferBankSaveRequestDTO:
        """Test TransferBankSaveRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferBankSaveRequestDTO`
        """
        model = TransferBankSaveRequestDTO()
        if include_optional:
            return TransferBankSaveRequestDTO(
                code = '237'
            )
        else:
            return TransferBankSaveRequestDTO(
                code = '237',
        )
        """

    def testTransferBankSaveRequestDTO(self):
        """Test TransferBankSaveRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
