# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.api.assinaturas_api import AssinaturasApi


class TestAssinaturasApi(unittest.TestCase):
    """AssinaturasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssinaturasApi()

    def tearDown(self) -> None:
        pass

    def test_atualizar_assinatura_existente(self) -> None:
        """Test case for atualizar_assinatura_existente

        Atualizar assinatura existente
        """
        pass

    def test_atualizar_cartao_de_credito_assinatura(self) -> None:
        """Test case for atualizar_cartao_de_credito_assinatura

        Atualiza o cartão de crédito sem efetuar cobrança
        """
        pass

    def test_atualizar_configuracao_para_emissao_de_notas_fiscais(self) -> None:
        """Test case for atualizar_configuracao_para_emissao_de_notas_fiscais

        Atualizar configuração para emissão de Notas Fiscais
        """
        pass

    def test_criar_assinatura_com_cartao_de_credito(self) -> None:
        """Test case for criar_assinatura_com_cartao_de_credito

        Criar assinatura com cartão de crédito
        """
        pass

    def test_criar_configuracao_para_emissao_de_notas_fiscais(self) -> None:
        """Test case for criar_configuracao_para_emissao_de_notas_fiscais

        Criar configuração para emissão de Notas Fiscais
        """
        pass

    def test_criar_nova_assinatura(self) -> None:
        """Test case for criar_nova_assinatura

        Criar nova assinatura
        """
        pass

    def test_gerar_carne_de_assinatura(self) -> None:
        """Test case for gerar_carne_de_assinatura

        Gerar carnê de assinatura
        """
        pass

    def test_listar_assinaturas(self) -> None:
        """Test case for listar_assinaturas

        Listar assinaturas
        """
        pass

    def test_listar_cobrancas_de_uma_assinatura(self) -> None:
        """Test case for listar_cobrancas_de_uma_assinatura

        Listar cobranças de uma assinatura
        """
        pass

    def test_listar_notas_fiscais_das_cobrancas_de_uma_assinatura(self) -> None:
        """Test case for listar_notas_fiscais_das_cobrancas_de_uma_assinatura

        Listar notas fiscais das cobranças de uma assinatura
        """
        pass

    def test_recuperar_configuracao_para_emissao_de_notas_fiscais(self) -> None:
        """Test case for recuperar_configuracao_para_emissao_de_notas_fiscais

        Recuperar configuração para emissão de notas fiscais
        """
        pass

    def test_recuperar_uma_unica_assinatura(self) -> None:
        """Test case for recuperar_uma_unica_assinatura

        Recuperar uma única assinatura
        """
        pass

    def test_remover_assinatura(self) -> None:
        """Test case for remover_assinatura

        Remover assinatura
        """
        pass

    def test_remover_configuracao_para_emissao_de_notas_fiscais(self) -> None:
        """Test case for remover_configuracao_para_emissao_de_notas_fiscais

        Remover configuração para emissão de Notas Fiscais
        """
        pass


if __name__ == '__main__':
    unittest.main()
