# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_token_bucket_get_address_key_response_dto import PixTokenBucketGetAddressKeyResponseDTO

class TestPixTokenBucketGetAddressKeyResponseDTO(unittest.TestCase):
    """PixTokenBucketGetAddressKeyResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixTokenBucketGetAddressKeyResponseDTO:
        """Test PixTokenBucketGetAddressKeyResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixTokenBucketGetAddressKeyResponseDTO`
        """
        model = PixTokenBucketGetAddressKeyResponseDTO()
        if include_optional:
            return PixTokenBucketGetAddressKeyResponseDTO(
                capacity = 56,
                remaining = 56
            )
        else:
            return PixTokenBucketGetAddressKeyResponseDTO(
        )
        """

    def testPixTokenBucketGetAddressKeyResponseDTO(self):
        """Test PixTokenBucketGetAddressKeyResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
