# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.api.recargas_de_celular_api import RecargasDeCelularApi


class TestRecargasDeCelularApi(unittest.TestCase):
    """RecargasDeCelularApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecargasDeCelularApi()

    def tearDown(self) -> None:
        pass

    def test_buscar_qual_provedor_o_numero_pertence_eos_valores_disponiveis_para_recarga(self) -> None:
        """Test case for buscar_qual_provedor_o_numero_pertence_eos_valores_disponiveis_para_recarga

        Buscar qual provedor o número pertence e os valores disponíveis para recarga
        """
        pass

    def test_cancelar_uma_recarga_de_celular(self) -> None:
        """Test case for cancelar_uma_recarga_de_celular

        Cancelar uma recarga de celular
        """
        pass

    def test_listar_recargas_de_celular(self) -> None:
        """Test case for listar_recargas_de_celular

        Listar recargas de celular
        """
        pass

    def test_recuperar_uma_unica_recarga_de_celular(self) -> None:
        """Test case for recuperar_uma_unica_recarga_de_celular

        Recuperar uma única recarga de celular
        """
        pass

    def test_solicitar_recarga(self) -> None:
        """Test case for solicitar_recarga

        Solicitar recarga
        """
        pass


if __name__ == '__main__':
    unittest.main()
