# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.webhook_config_update_request_webhook_event import WebhookConfigUpdateRequestWebhookEvent

class TestWebhookConfigUpdateRequestWebhookEvent(unittest.TestCase):
    """WebhookConfigUpdateRequestWebhookEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookConfigUpdateRequestWebhookEvent(self):
        """Test WebhookConfigUpdateRequestWebhookEvent"""
        # inst = WebhookConfigUpdateRequestWebhookEvent()

if __name__ == '__main__':
    unittest.main()
