# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.my_account_get_account_fees_anticipation_credit_card_dto import MyAccountGetAccountFeesAnticipationCreditCardDTO

class TestMyAccountGetAccountFeesAnticipationCreditCardDTO(unittest.TestCase):
    """MyAccountGetAccountFeesAnticipationCreditCardDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MyAccountGetAccountFeesAnticipationCreditCardDTO:
        """Test MyAccountGetAccountFeesAnticipationCreditCardDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MyAccountGetAccountFeesAnticipationCreditCardDTO`
        """
        model = MyAccountGetAccountFeesAnticipationCreditCardDTO()
        if include_optional:
            return MyAccountGetAccountFeesAnticipationCreditCardDTO(
                detached_monthly_fee_value = 2.49,
                installment_monthly_fee_value = 2
            )
        else:
            return MyAccountGetAccountFeesAnticipationCreditCardDTO(
        )
        """

    def testMyAccountGetAccountFeesAnticipationCreditCardDTO(self):
        """Test MyAccountGetAccountFeesAnticipationCreditCardDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
