# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_original_transaction_response_dto import PixOriginalTransactionResponseDTO

class TestPixOriginalTransactionResponseDTO(unittest.TestCase):
    """PixOriginalTransactionResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixOriginalTransactionResponseDTO:
        """Test PixOriginalTransactionResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixOriginalTransactionResponseDTO`
        """
        model = PixOriginalTransactionResponseDTO()
        if include_optional:
            return PixOriginalTransactionResponseDTO(
                id = '',
                end_to_end_identifier = '',
                value = 1.337,
                effective_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return PixOriginalTransactionResponseDTO(
        )
        """

    def testPixOriginalTransactionResponseDTO(self):
        """Test PixOriginalTransactionResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
