# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.fiscal_info_tax_situation_code_list_response_dto import FiscalInfoTaxSituationCodeListResponseDTO

class TestFiscalInfoTaxSituationCodeListResponseDTO(unittest.TestCase):
    """FiscalInfoTaxSituationCodeListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalInfoTaxSituationCodeListResponseDTO:
        """Test FiscalInfoTaxSituationCodeListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalInfoTaxSituationCodeListResponseDTO`
        """
        model = FiscalInfoTaxSituationCodeListResponseDTO()
        if include_optional:
            return FiscalInfoTaxSituationCodeListResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.fiscal_info_tax_situation_code_response_dto.FiscalInfoTaxSituationCodeResponseDTO(
                        code = '200001', 
                        description = 'Tributação com alíquotas uniformes reduzidas', 
                        is_subject_to_ibs_cbs_taxation = True, 
                        is_base_reduction_percent_applicable = False, 
                        is_deferment_applicable = False, )
                    ]
            )
        else:
            return FiscalInfoTaxSituationCodeListResponseDTO(
        )
        """

    def testFiscalInfoTaxSituationCodeListResponseDTO(self):
        """Test FiscalInfoTaxSituationCodeListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
