# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.customer_save_request_dto import CustomerSaveRequestDTO

class TestCustomerSaveRequestDTO(unittest.TestCase):
    """CustomerSaveRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerSaveRequestDTO:
        """Test CustomerSaveRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerSaveRequestDTO`
        """
        model = CustomerSaveRequestDTO()
        if include_optional:
            return CustomerSaveRequestDTO(
                name = 'John Doe',
                cpf_cnpj = '24971563792',
                email = 'john.doe@asaas.com.br',
                phone = '4738010919',
                mobile_phone = '4799376637',
                address = 'Av. Paulista',
                address_number = '150',
                complement = 'Sala 201',
                province = 'Centro',
                postal_code = '01310-000',
                external_reference = '12987382',
                notification_disabled = False,
                additional_emails = 'john.doe@asaas.com,john.doe.silva@asaas.com.br',
                municipal_inscription = '46683695908',
                state_inscription = '646681195275',
                observations = 'ótimo pagador, nenhum problema até o momento',
                group_name = '',
                company = '',
                foreign_customer = False
            )
        else:
            return CustomerSaveRequestDTO(
                name = 'John Doe',
                cpf_cnpj = '24971563792',
        )
        """

    def testCustomerSaveRequestDTO(self):
        """Test CustomerSaveRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
