# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.api.pix_automatico_api import PixAutomticoApi


class TestPixAutomticoApi(unittest.TestCase):
    """PixAutomticoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PixAutomticoApi()

    def tearDown(self) -> None:
        pass

    def test_cancelar_uma_autorizacao_pix_automatico(self) -> None:
        """Test case for cancelar_uma_autorizacao_pix_automatico

        Cancelar uma autorização
        """
        pass

    def test_criar_uma_autorizacao_pix_automatico(self) -> None:
        """Test case for criar_uma_autorizacao_pix_automatico

        Criar uma autorização
        """
        pass

    def test_listar_autorizacoes_pix_automatico(self) -> None:
        """Test case for listar_autorizacoes_pix_automatico

        Listar autorizações
        """
        pass

    def test_listar_instrucoes_de_pagamento_pix_automatico(self) -> None:
        """Test case for listar_instrucoes_de_pagamento_pix_automatico

        Listar instruções de pagamento
        """
        pass

    def test_recuperar_uma_unica_autorizacao_pix_automatico(self) -> None:
        """Test case for recuperar_uma_unica_autorizacao_pix_automatico

        Recuperar uma única autorização
        """
        pass

    def test_recuperar_uma_unica_instrucao_de_pagamento_pix_automatico(self) -> None:
        """Test case for recuperar_uma_unica_instrucao_de_pagamento_pix_automatico

        Recuperar uma única instrução de pagamento
        """
        pass


if __name__ == '__main__':
    unittest.main()
