# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_dunning_payments_available_for_dunning_response_data_type_simulation_item_dto import PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO

class TestPaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO(unittest.TestCase):
    """PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO:
        """Test PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO`
        """
        model = PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO()
        if include_optional:
            return PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO(
                type = 'CREDIT_BUREAU',
                is_allowed = True,
                not_allowed_reason = '',
                fee_value = 0,
                net_value = 0,
                start_date = '2020-05-27'
            )
        else:
            return PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO(
        )
        """

    def testPaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO(self):
        """Test PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
