# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.anticipation_limits_response_dto import AnticipationLimitsResponseDTO

class TestAnticipationLimitsResponseDTO(unittest.TestCase):
    """AnticipationLimitsResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnticipationLimitsResponseDTO:
        """Test AnticipationLimitsResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnticipationLimitsResponseDTO`
        """
        model = AnticipationLimitsResponseDTO()
        if include_optional:
            return AnticipationLimitsResponseDTO(
                credit_card = asaas.models.anticipation_limits_info_response_dto.AnticipationLimitsInfoResponseDTO(
                    total = 50000, 
                    available = 35360.7, ),
                bank_slip = asaas.models.anticipation_limits_info_response_dto.AnticipationLimitsInfoResponseDTO(
                    total = 50000, 
                    available = 35360.7, )
            )
        else:
            return AnticipationLimitsResponseDTO(
        )
        """

    def testAnticipationLimitsResponseDTO(self):
        """Test AnticipationLimitsResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
