# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_lean_list_response_dto import PaymentLeanListResponseDTO

class TestPaymentLeanListResponseDTO(unittest.TestCase):
    """PaymentLeanListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLeanListResponseDTO:
        """Test PaymentLeanListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLeanListResponseDTO`
        """
        model = PaymentLeanListResponseDTO()
        if include_optional:
            return PaymentLeanListResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.payment_lean_get_response_dto.PaymentLeanGetResponseDTO(
                        object = 'payment', 
                        id = 'pay_080225913252', 
                        date_created = 'Thu Mar 09 21:00:00 BRT 2017', 
                        customer_id = 'cus_G7Dvo4iphUNk', 
                        subscription_id = '', 
                        installment_id = '', 
                        payment_link_id = '', 
                        value = 129.9, 
                        net_value = 124.9, 
                        original_value = 1.337, 
                        interest_value = 1.337, 
                        description = 'Pedido 056984', 
                        billing_type = 'BOLETO', 
                        can_be_paid_after_due_date = True, 
                        confirmed_date = 'Thu Mar 09 21:00:00 BRT 2017', 
                        pix_transaction_id = '', 
                        status = 'PENDING', 
                        due_date = 'Fri Jun 09 21:00:00 BRT 2017', 
                        original_due_date = 'Fri Jun 09 21:00:00 BRT 2017', 
                        payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        customer_payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        installment_number = 56, 
                        external_reference = '056984', 
                        deleted = False, 
                        anticipated = False, 
                        anticipable = False, 
                        credit_date = '2017-03-10', 
                        transaction_receipt_url = '', 
                        duplicated_payment_id = '', 
                        discount = asaas.models.payment_discount_dto.PaymentDiscountDTO(
                            value = 10, 
                            due_date_limit_days = 0, 
                            type = 'PERCENTAGE', ), 
                        fine = asaas.models.payment_fine_response_dto.PaymentFineResponseDTO(
                            value = 1, ), 
                        interest = asaas.models.payment_interest_response_dto.PaymentInterestResponseDTO(
                            value = 2, ), 
                        postal_service = False, )
                    ]
            )
        else:
            return PaymentLeanListResponseDTO(
        )
        """

    def testPaymentLeanListResponseDTO(self):
        """Test PaymentLeanListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
