# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.checkout_session_response_billing_type import CheckoutSessionResponseBillingType

class TestCheckoutSessionResponseBillingType(unittest.TestCase):
    """CheckoutSessionResponseBillingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckoutSessionResponseBillingType(self):
        """Test CheckoutSessionResponseBillingType"""
        # inst = CheckoutSessionResponseBillingType()

if __name__ == '__main__':
    unittest.main()
