# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_qr_code_decode_request_dto import PixQrCodeDecodeRequestDTO

class TestPixQrCodeDecodeRequestDTO(unittest.TestCase):
    """PixQrCodeDecodeRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixQrCodeDecodeRequestDTO:
        """Test PixQrCodeDecodeRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PixQrCodeDecodeRequestDTO`
        """
        model = PixQrCodeDecodeRequestDTO()
        if include_optional:
            return PixQrCodeDecodeRequestDTO(
                payload = '00020101021226730014br.gov.bcb.pix2551pix-h.asaas.com/pixqrcode/cobv/pay_76575613967995145204000053039865802BR5905ASAAS6009Joinville61088922827162070503***63045E7A',
                change_value = 1.337,
                expected_payment_date = 'Wed Dec 31 21:00:00 BRT 2025'
            )
        else:
            return PixQrCodeDecodeRequestDTO(
                payload = '00020101021226730014br.gov.bcb.pix2551pix-h.asaas.com/pixqrcode/cobv/pay_76575613967995145204000053039865802BR5905ASAAS6009Joinville61088922827162070503***63045E7A',
        )
        """

    def testPixQrCodeDecodeRequestDTO(self):
        """Test PixQrCodeDecodeRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
