# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_document_get_response_dto import PaymentDocumentGetResponseDTO

class TestPaymentDocumentGetResponseDTO(unittest.TestCase):
    """PaymentDocumentGetResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDocumentGetResponseDTO:
        """Test PaymentDocumentGetResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDocumentGetResponseDTO`
        """
        model = PaymentDocumentGetResponseDTO()
        if include_optional:
            return PaymentDocumentGetResponseDTO(
                object = 'paymentDocument',
                id = '609a3f98-8db7-4a89-b511-de4c3be6d462',
                name = 'Nota Fiscal.pdf',
                type = 'INVOICE',
                available_after_payment = True,
                file = asaas.models.payment_document_file_response_dto.PaymentDocumentFileResponseDTO(
                    public_id = 'TSrLvzPGF7HPQhYu9OZhZSBX3mm1sxpToEcFm30imOM3sKEjhzCc1zAIuqQ7n11', 
                    original_name = 'Nota Fiscal.pdf', 
                    size = 14499, 
                    extension = 'pdf', 
                    preview_url = 'https://www.asaas.com/file/preview/TSrLvzPGF7HPQhYu9OZhZSBX3mm1sxpToEcFm30imOM3sKEjhzCc1zAIuqQ7n11', 
                    download_url = 'https://www.asaas.com/file/public/download/TSrLvzPGF7HPQhYu9OZhZSBX3mm1sxpToEcFm30imOM3sKEjhzCc1zAIuqQ7n11', ),
                deleted = False
            )
        else:
            return PaymentDocumentGetResponseDTO(
        )
        """

    def testPaymentDocumentGetResponseDTO(self):
        """Test PaymentDocumentGetResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
