# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.api.cobrancas_com_dados_resumidos_api import CobranasComDadosResumidosApi


class TestCobranasComDadosResumidosApi(unittest.TestCase):
    """CobranasComDadosResumidosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CobranasComDadosResumidosApi()

    def tearDown(self) -> None:
        pass

    def test_atualizar_cobranca_existente_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for atualizar_cobranca_existente_com_dados_resumidos_na_resposta

        Atualizar cobrança existente com dados resumidos na resposta
        """
        pass

    def test_capturar_cobranca_com_pre_autorizacao_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for capturar_cobranca_com_pre_autorizacao_com_dados_resumidos_na_resposta

        Capturar cobrança com Pré-Autorização com dados resumidos na resposta
        """
        pass

    def test_confirmar_recebimento_em_dinheiro_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for confirmar_recebimento_em_dinheiro_com_dados_resumidos_na_resposta

        Confirmar recebimento em dinheiro com dados resumidos na resposta
        """
        pass

    def test_criar_cobranca_com_cartao_de_credito_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for criar_cobranca_com_cartao_de_credito_com_dados_resumidos_na_resposta

        Criar cobrança com cartão de crédito com dados resumidos na resposta
        """
        pass

    def test_criar_nova_cobranca_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for criar_nova_cobranca_com_dados_resumidos_na_resposta

        Criar nova cobrança com dados resumidos na resposta
        """
        pass

    def test_desfazer_confirmacao_de_recebimento_em_dinheiro_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for desfazer_confirmacao_de_recebimento_em_dinheiro_com_dados_resumidos_na_resposta

        Desfazer confirmação de recebimento em dinheiro com dados resumidos na resposta
        """
        pass

    def test_estornar_cobranca_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for estornar_cobranca_com_dados_resumidos_na_resposta

        Estornar cobrança com dados resumidos na resposta
        """
        pass

    def test_excluir_cobranca_com_dados_resumidos(self) -> None:
        """Test case for excluir_cobranca_com_dados_resumidos

        Excluir cobrança com dados resumidos
        """
        pass

    def test_listar_cobrancas_com_dados_resumidos(self) -> None:
        """Test case for listar_cobrancas_com_dados_resumidos

        Listar cobranças com dados resumidos
        """
        pass

    def test_recuperar_uma_unica_cobranca_com_dados_resumidos(self) -> None:
        """Test case for recuperar_uma_unica_cobranca_com_dados_resumidos

        Recuperar uma única cobrança com dados resumidos
        """
        pass

    def test_restaurar_cobranca_removida_com_dados_resumidos_na_resposta(self) -> None:
        """Test case for restaurar_cobranca_removida_com_dados_resumidos_na_resposta

        Restaurar cobrança removida com dados resumidos na resposta
        """
        pass


if __name__ == '__main__':
    unittest.main()
