# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.subscription_delete_invoice_config_response_dto import SubscriptionDeleteInvoiceConfigResponseDTO

class TestSubscriptionDeleteInvoiceConfigResponseDTO(unittest.TestCase):
    """SubscriptionDeleteInvoiceConfigResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionDeleteInvoiceConfigResponseDTO:
        """Test SubscriptionDeleteInvoiceConfigResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionDeleteInvoiceConfigResponseDTO`
        """
        model = SubscriptionDeleteInvoiceConfigResponseDTO()
        if include_optional:
            return SubscriptionDeleteInvoiceConfigResponseDTO(
                deleted = True,
                id = 'sub_VXJBYgP2u0eO'
            )
        else:
            return SubscriptionDeleteInvoiceConfigResponseDTO(
        )
        """

    def testSubscriptionDeleteInvoiceConfigResponseDTO(self):
        """Test SubscriptionDeleteInvoiceConfigResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
