# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.fiscal_info_operation_indicator_code_response_dto import FiscalInfoOperationIndicatorCodeResponseDTO

class TestFiscalInfoOperationIndicatorCodeResponseDTO(unittest.TestCase):
    """FiscalInfoOperationIndicatorCodeResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalInfoOperationIndicatorCodeResponseDTO:
        """Test FiscalInfoOperationIndicatorCodeResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalInfoOperationIndicatorCodeResponseDTO`
        """
        model = FiscalInfoOperationIndicatorCodeResponseDTO()
        if include_optional:
            return FiscalInfoOperationIndicatorCodeResponseDTO(
                code = '020101',
                description = 'Execução de operações com bem imóvel, bem imaterial, inclusive direito, relacionado a bem imóvel'
            )
        else:
            return FiscalInfoOperationIndicatorCodeResponseDTO(
        )
        """

    def testFiscalInfoOperationIndicatorCodeResponseDTO(self):
        """Test FiscalInfoOperationIndicatorCodeResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
