# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_dunning_payments_available_for_dunning_response_data_type_simulation_item_payment_dunning_type import PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemPaymentDunningType

class TestPaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemPaymentDunningType(unittest.TestCase):
    """PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemPaymentDunningType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemPaymentDunningType(self):
        """Test PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemPaymentDunningType"""
        # inst = PaymentDunningPaymentsAvailableForDunningResponseDataTypeSimulationItemPaymentDunningType()

if __name__ == '__main__':
    unittest.main()
