# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_address_key_list_request_pix_address_key_status import PixAddressKeyListRequestPixAddressKeyStatus

class TestPixAddressKeyListRequestPixAddressKeyStatus(unittest.TestCase):
    """PixAddressKeyListRequestPixAddressKeyStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPixAddressKeyListRequestPixAddressKeyStatus(self):
        """Test PixAddressKeyListRequestPixAddressKeyStatus"""
        # inst = PixAddressKeyListRequestPixAddressKeyStatus()

if __name__ == '__main__':
    unittest.main()
