# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.customer_api_access_token_base_response_dto import CustomerApiAccessTokenBaseResponseDTO

class TestCustomerApiAccessTokenBaseResponseDTO(unittest.TestCase):
    """CustomerApiAccessTokenBaseResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerApiAccessTokenBaseResponseDTO:
        """Test CustomerApiAccessTokenBaseResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerApiAccessTokenBaseResponseDTO`
        """
        model = CustomerApiAccessTokenBaseResponseDTO()
        if include_optional:
            return CustomerApiAccessTokenBaseResponseDTO(
                id = 'b6bff0c5-38c6-496a-a3a8-105b31d5bcfe',
                name = 'My API Access Token',
                enabled = False,
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                projected_expiration_date_by_lack_of_use = 'Sun May 31 21:00:00 BRT 2026'
            )
        else:
            return CustomerApiAccessTokenBaseResponseDTO(
        )
        """

    def testCustomerApiAccessTokenBaseResponseDTO(self):
        """Test CustomerApiAccessTokenBaseResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
