# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.account_document_delete_response_dto import AccountDocumentDeleteResponseDTO

class TestAccountDocumentDeleteResponseDTO(unittest.TestCase):
    """AccountDocumentDeleteResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountDocumentDeleteResponseDTO:
        """Test AccountDocumentDeleteResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountDocumentDeleteResponseDTO`
        """
        model = AccountDocumentDeleteResponseDTO()
        if include_optional:
            return AccountDocumentDeleteResponseDTO(
                deleted = True,
                id = '8d257732-2220-11ec-b695-b6af4a64184d'
            )
        else:
            return AccountDocumentDeleteResponseDTO(
        )
        """

    def testAccountDocumentDeleteResponseDTO(self):
        """Test AccountDocumentDeleteResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
