# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.subscription_invoice_config_get_response_dto import SubscriptionInvoiceConfigGetResponseDTO

class TestSubscriptionInvoiceConfigGetResponseDTO(unittest.TestCase):
    """SubscriptionInvoiceConfigGetResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionInvoiceConfigGetResponseDTO:
        """Test SubscriptionInvoiceConfigGetResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionInvoiceConfigGetResponseDTO`
        """
        model = SubscriptionInvoiceConfigGetResponseDTO()
        if include_optional:
            return SubscriptionInvoiceConfigGetResponseDTO(
                municipal_service_id = '',
                municipal_service_code = '1.01',
                municipal_service_name = '',
                deductions = 55,
                invoice_creation_period = 'ON_PAYMENT_CONFIRMATION',
                days_before_due_date = 56,
                received_only = True,
                observations = 'Referente aos trabalhos de março',
                taxes = asaas.models.invoice_taxes_dto.InvoiceTaxesDTO(
                    retain_iss = True, 
                    cofins = 1, 
                    csll = 1, 
                    inss = 1, 
                    ir = 1, 
                    pis = 1, 
                    iss = 1, )
            )
        else:
            return SubscriptionInvoiceConfigGetResponseDTO(
        )
        """

    def testSubscriptionInvoiceConfigGetResponseDTO(self):
        """Test SubscriptionInvoiceConfigGetResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
