# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_limits_response_dto import PaymentLimitsResponseDTO

class TestPaymentLimitsResponseDTO(unittest.TestCase):
    """PaymentLimitsResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLimitsResponseDTO:
        """Test PaymentLimitsResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLimitsResponseDTO`
        """
        model = PaymentLimitsResponseDTO()
        if include_optional:
            return PaymentLimitsResponseDTO(
                creation = asaas.models.payment_limits_response_creation_dto.PaymentLimitsResponseCreationDTO(
                    daily = asaas.models.payment_limits_response_creation_daily_dto.PaymentLimitsResponseCreationDailyDTO(
                        limit = 10, 
                        used = 5, 
                        was_reached = True, ), )
            )
        else:
            return PaymentLimitsResponseDTO(
        )
        """

    def testPaymentLimitsResponseDTO(self):
        """Test PaymentLimitsResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
