# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.bill_save_request_dto import BillSaveRequestDTO

class TestBillSaveRequestDTO(unittest.TestCase):
    """BillSaveRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillSaveRequestDTO:
        """Test BillSaveRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillSaveRequestDTO`
        """
        model = BillSaveRequestDTO()
        if include_optional:
            return BillSaveRequestDTO(
                identification_field = '03399.77779 29900.000000 04751.101017 1 81510000002990',
                schedule_date = '2020-03-15',
                description = 'Celular 03/12',
                discount = 0,
                interest = 0,
                fine = 0,
                due_date = 'Sun Mar 29 21:00:00 BRT 2020',
                value = 29,
                external_reference = '056984'
            )
        else:
            return BillSaveRequestDTO(
                identification_field = '03399.77779 29900.000000 04751.101017 1 81510000002990',
        )
        """

    def testBillSaveRequestDTO(self):
        """Test BillSaveRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
