# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.transfer_list_response_dto import TransferListResponseDTO

class TestTransferListResponseDTO(unittest.TestCase):
    """TransferListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferListResponseDTO:
        """Test TransferListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferListResponseDTO`
        """
        model = TransferListResponseDTO()
        if include_optional:
            return TransferListResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.transfer_get_response_dto.TransferGetResponseDTO(
                        object = 'transfer', 
                        id = '777eb7c8-b1a2-4356-8fd8-a1b0644b5282', 
                        type = 'BANK_ACCOUNT', 
                        date_created = 'Wed May 01 21:00:00 BRT 2019', 
                        value = 1000, 
                        net_value = 0, 
                        status = 'PENDING', 
                        transfer_fee = 0, 
                        effective_date = 'Wed May 01 21:00:00 BRT 2019', 
                        schedule_date = 'Wed May 01 21:00:00 BRT 2019', 
                        end_to_end_identifier = '', 
                        authorized = True, 
                        fail_reason = '', 
                        external_reference = '', 
                        transaction_receipt_url = '', 
                        operation_type = 'TED', 
                        description = '', 
                        recurring = '', 
                        bank_account = asaas.models.transfer_bank_account_get_response_dto.TransferBankAccountGetResponseDTO(
                            bank = asaas.models.transfer_bank_get_response_dto.TransferBankGetResponseDTO(
                                ispb = '', 
                                code = '001', 
                                name = 'Banco do Brasil', ), 
                            account_name = 'Conta Banco do Brasil', 
                            owner_name = 'John Doe', 
                            cpf_cnpj = '***.143.689-**', 
                            agency = '1263', 
                            agency_digit = '3', 
                            account = '9999991', 
                            account_digit = '1', 
                            pix_address_key = '', ), )
                    ]
            )
        else:
            return TransferListResponseDTO(
        )
        """

    def testTransferListResponseDTO(self):
        """Test TransferListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
