# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.fiscal_info_municipal_options_get_response_dto import FiscalInfoMunicipalOptionsGetResponseDTO

class TestFiscalInfoMunicipalOptionsGetResponseDTO(unittest.TestCase):
    """FiscalInfoMunicipalOptionsGetResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalInfoMunicipalOptionsGetResponseDTO:
        """Test FiscalInfoMunicipalOptionsGetResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalInfoMunicipalOptionsGetResponseDTO`
        """
        model = FiscalInfoMunicipalOptionsGetResponseDTO()
        if include_optional:
            return FiscalInfoMunicipalOptionsGetResponseDTO(
                authentication_type = 'CERTIFICATE',
                supports_cancellation = True,
                uses_special_tax_regimes = True,
                uses_service_list_item = True,
                special_tax_regimes_list = [
                    asaas.models.fiscal_info_municipal_options_special_tax_regimes_dto.FiscalInfoMunicipalOptionsSpecialTaxRegimesDTO(
                        label = 'Microempresa Municipal', 
                        value = '1', )
                    ],
                national_portal_tax_calculation_regime_list = [
                    asaas.models.fiscal_info_municipal_options_national_portal_tax_calculation_regime_dto.FiscalInfoMunicipalOptionsNationalPortalTaxCalculationRegimeDTO(
                        label = 'Regime de apuração dos tributos federais e municipal pelo SN', 
                        value = '0', )
                    ],
                national_portal_tax_calculation_regime_help = 'Isso identifica o regime de apuração tributária pelo Simples Nacional de sua empresa, se desejar deixar sem nenhuma opção marcada selecione a opção "Nenhum". Deve ser preenchido somente por empresas enquadradas como ME ou EPP optantes do Simples Nacional. Consulte a necessidade desta informação com a sua prefeitura ou a sua contabilidade.',
                municipal_inscription_help = 'Informe somente os números sem ponto nem formatação (se contiver letras, insira sempre em maiúscula).

Exemplos válidos: 4301000010 ou 131436001X',
                special_tax_regime_help = 'Isso identifica o regime de tributação de sua empresa, se desejar deixar sem nenhuma opção marcada selecione o traço ("-").
 
 Empresas do simples nacional geralmente optam pelo ME ou ME EPP',
                service_list_item_help = 'Informe aqui o item da lista de serviço, é também um identificador do serviço prestado.
 
 Você precisa preencher o item da lista de serviço mantendo a formatação.
 Exemplos válidos: 17.02 ou 8.02',
                digital_certificated_help = 'Sua prefeitura exige a utilização de certificado digital, portanto, inclua aqui o arquivo de seu certificado A1.',
                access_token_help = '',
                municipal_service_code_help = 'Informe aqui o código municipal que identifica o serviço prestado na nota fiscal. 
Em algumas cidades esse código é conhecido como código de tributação ou CTISS.

Exemplo válido: 010300388'
            )
        else:
            return FiscalInfoMunicipalOptionsGetResponseDTO(
        )
        """

    def testFiscalInfoMunicipalOptionsGetResponseDTO(self):
        """Test FiscalInfoMunicipalOptionsGetResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
