# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_document_delete_response_dto import PaymentDocumentDeleteResponseDTO

class TestPaymentDocumentDeleteResponseDTO(unittest.TestCase):
    """PaymentDocumentDeleteResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDocumentDeleteResponseDTO:
        """Test PaymentDocumentDeleteResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDocumentDeleteResponseDTO`
        """
        model = PaymentDocumentDeleteResponseDTO()
        if include_optional:
            return PaymentDocumentDeleteResponseDTO(
                deleted = True,
                id = '609a3f98-8db7-4a89-b511-de4c3be6d462'
            )
        else:
            return PaymentDocumentDeleteResponseDTO(
        )
        """

    def testPaymentDocumentDeleteResponseDTO(self):
        """Test PaymentDocumentDeleteResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
