# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.checkout_session_callback_dto import CheckoutSessionCallbackDTO

class TestCheckoutSessionCallbackDTO(unittest.TestCase):
    """CheckoutSessionCallbackDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionCallbackDTO:
        """Test CheckoutSessionCallbackDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionCallbackDTO`
        """
        model = CheckoutSessionCallbackDTO()
        if include_optional:
            return CheckoutSessionCallbackDTO(
                success_url = 'https://example.com/asaas/checkout/success',
                cancel_url = 'https://example.com/asaas/checkout/cancel',
                expired_url = 'https://example.com/asaas/checkout/expired'
            )
        else:
            return CheckoutSessionCallbackDTO(
                success_url = 'https://example.com/asaas/checkout/success',
                cancel_url = 'https://example.com/asaas/checkout/cancel',
        )
        """

    def testCheckoutSessionCallbackDTO(self):
        """Test CheckoutSessionCallbackDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
