# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.fiscal_info_list_municipal_services_response_data_dto import FiscalInfoListMunicipalServicesResponseDataDTO

class TestFiscalInfoListMunicipalServicesResponseDataDTO(unittest.TestCase):
    """FiscalInfoListMunicipalServicesResponseDataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalInfoListMunicipalServicesResponseDataDTO:
        """Test FiscalInfoListMunicipalServicesResponseDataDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalInfoListMunicipalServicesResponseDataDTO`
        """
        model = FiscalInfoListMunicipalServicesResponseDataDTO()
        if include_optional:
            return FiscalInfoListMunicipalServicesResponseDataDTO(
                id = '3544',
                description = '1.01 - Análise e desenvolvimento de sistemas',
                iss_tax = 0.5
            )
        else:
            return FiscalInfoListMunicipalServicesResponseDataDTO(
        )
        """

    def testFiscalInfoListMunicipalServicesResponseDataDTO(self):
        """Test FiscalInfoListMunicipalServicesResponseDataDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
