# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_chargeback_response_dto import PaymentChargebackResponseDTO

class TestPaymentChargebackResponseDTO(unittest.TestCase):
    """PaymentChargebackResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentChargebackResponseDTO:
        """Test PaymentChargebackResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentChargebackResponseDTO`
        """
        model = PaymentChargebackResponseDTO()
        if include_optional:
            return PaymentChargebackResponseDTO(
                id = '8e784c3e-afe8-4844-bb93-6b445763',
                payment = 'pay_pBtDdshgBD2Rt',
                installment = 'b8dd74c-d078-40a0-9ae1-61a66c61a204',
                customer_account = 'cus_000000004085',
                status = 'DONE',
                reason = 'COMMERCIAL_DISAGREEMENT',
                dispute_start_date = 'Sat Nov 09 21:00:00 BRT 2024',
                value = 2323.45,
                payment_date = 'Sat Mar 09 21:00:00 BRT 2024',
                credit_card = asaas.models.chargeback_credit_card_response_dto.ChargebackCreditCardResponseDTO(
                    number = '8829', 
                    brand = 'VISA', ),
                dispute_status = 'ACCEPTED',
                deadline_to_send_dispute_documents = 'Mon Dec 09 21:00:00 BRT 2024'
            )
        else:
            return PaymentChargebackResponseDTO(
        )
        """

    def testPaymentChargebackResponseDTO(self):
        """Test PaymentChargebackResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
