# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_dunning_list_history_response_dto import PaymentDunningListHistoryResponseDTO

class TestPaymentDunningListHistoryResponseDTO(unittest.TestCase):
    """PaymentDunningListHistoryResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDunningListHistoryResponseDTO:
        """Test PaymentDunningListHistoryResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDunningListHistoryResponseDTO`
        """
        model = PaymentDunningListHistoryResponseDTO()
        if include_optional:
            return PaymentDunningListHistoryResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.payment_dunning_list_history_response_data_dto.PaymentDunningListHistoryResponseDataDTO(
                        status = 'NEGOTIATED', 
                        description = 'Negativação negociada com o cliente. O pagamento será iniciado.', 
                        event_date = '2019-02-20', )
                    ]
            )
        else:
            return PaymentDunningListHistoryResponseDTO(
        )
        """

    def testPaymentDunningListHistoryResponseDTO(self):
        """Test PaymentDunningListHistoryResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
