# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.pix_address_key_save_request_pix_address_key_type import PixAddressKeySaveRequestPixAddressKeyType

class TestPixAddressKeySaveRequestPixAddressKeyType(unittest.TestCase):
    """PixAddressKeySaveRequestPixAddressKeyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPixAddressKeySaveRequestPixAddressKeyType(self):
        """Test PixAddressKeySaveRequestPixAddressKeyType"""
        # inst = PixAddressKeySaveRequestPixAddressKeyType()

if __name__ == '__main__':
    unittest.main()
