# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.payment_simulate_bank_slip_response_dto import PaymentSimulateBankSlipResponseDTO

class TestPaymentSimulateBankSlipResponseDTO(unittest.TestCase):
    """PaymentSimulateBankSlipResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSimulateBankSlipResponseDTO:
        """Test PaymentSimulateBankSlipResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSimulateBankSlipResponseDTO`
        """
        model = PaymentSimulateBankSlipResponseDTO()
        if include_optional:
            return PaymentSimulateBankSlipResponseDTO(
                net_value = 98.02,
                fee_value = 0.99,
                installment = asaas.models.payment_simulate_installment_response_dto.PaymentSimulateInstallmentResponseDTO(
                    payment_net_value = 48.52, 
                    payment_value = 50, )
            )
        else:
            return PaymentSimulateBankSlipResponseDTO(
        )
        """

    def testPaymentSimulateBankSlipResponseDTO(self):
        """Test PaymentSimulateBankSlipResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
