# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.my_account_get_account_fees_payment_bank_slip_dto import MyAccountGetAccountFeesPaymentBankSlipDTO

class TestMyAccountGetAccountFeesPaymentBankSlipDTO(unittest.TestCase):
    """MyAccountGetAccountFeesPaymentBankSlipDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MyAccountGetAccountFeesPaymentBankSlipDTO:
        """Test MyAccountGetAccountFeesPaymentBankSlipDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MyAccountGetAccountFeesPaymentBankSlipDTO`
        """
        model = MyAccountGetAccountFeesPaymentBankSlipDTO()
        if include_optional:
            return MyAccountGetAccountFeesPaymentBankSlipDTO(
                default_value = 6.96,
                discount_value = 3.99,
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                days_to_receive = 1
            )
        else:
            return MyAccountGetAccountFeesPaymentBankSlipDTO(
        )
        """

    def testMyAccountGetAccountFeesPaymentBankSlipDTO(self):
        """Test MyAccountGetAccountFeesPaymentBankSlipDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
