# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.customer_get_response_dto import CustomerGetResponseDTO

class TestCustomerGetResponseDTO(unittest.TestCase):
    """CustomerGetResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerGetResponseDTO:
        """Test CustomerGetResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerGetResponseDTO`
        """
        model = CustomerGetResponseDTO()
        if include_optional:
            return CustomerGetResponseDTO(
                object = 'customer',
                id = 'cus_000005401844',
                date_created = '2024-07-12',
                name = 'John Doe',
                email = 'john.doe@asaas.com.br',
                phone = '90999999999',
                mobile_phone = '90999999999',
                address = 'Av. Paulista',
                address_number = '150',
                complement = 'Sala 201',
                province = 'Centro',
                city = 12565,
                city_name = 'São Paulo',
                state = 'SP',
                country = 'Brasil',
                postal_code = '01310000',
                cpf_cnpj = '24971563792',
                person_type = 'FISICA',
                deleted = False,
                additional_emails = 'john.doe@asaas.com,john.doe.silva@asaas.com.br',
                external_reference = '12987382',
                notification_disabled = False,
                observations = 'ótimo pagador, nenhum problema até o momento',
                foreign_customer = False
            )
        else:
            return CustomerGetResponseDTO(
        )
        """

    def testCustomerGetResponseDTO(self):
        """Test CustomerGetResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
