# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.notification_batch_update_request_dto import NotificationBatchUpdateRequestDTO

class TestNotificationBatchUpdateRequestDTO(unittest.TestCase):
    """NotificationBatchUpdateRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationBatchUpdateRequestDTO:
        """Test NotificationBatchUpdateRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationBatchUpdateRequestDTO`
        """
        model = NotificationBatchUpdateRequestDTO()
        if include_optional:
            return NotificationBatchUpdateRequestDTO(
                customer = 'cus_000005401844',
                notifications = [
                    asaas.models.notification_batch_update_item_request_dto.NotificationBatchUpdateItemRequestDTO(
                        id = 'not_wuGp97JeCr7G', 
                        enabled = True, 
                        email_enabled_for_provider = True, 
                        sms_enabled_for_provider = True, 
                        email_enabled_for_customer = True, 
                        sms_enabled_for_customer = True, 
                        phone_call_enabled_for_customer = False, 
                        whatsapp_enabled_for_customer = False, 
                        schedule_offset = 1, )
                    ]
            )
        else:
            return NotificationBatchUpdateRequestDTO(
                customer = 'cus_000005401844',
        )
        """

    def testNotificationBatchUpdateRequestDTO(self):
        """Test NotificationBatchUpdateRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
