# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.fiscal_info_federal_service_code_list_response_dto import FiscalInfoFederalServiceCodeListResponseDTO

class TestFiscalInfoFederalServiceCodeListResponseDTO(unittest.TestCase):
    """FiscalInfoFederalServiceCodeListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FiscalInfoFederalServiceCodeListResponseDTO:
        """Test FiscalInfoFederalServiceCodeListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FiscalInfoFederalServiceCodeListResponseDTO`
        """
        model = FiscalInfoFederalServiceCodeListResponseDTO()
        if include_optional:
            return FiscalInfoFederalServiceCodeListResponseDTO(
                object = 'list',
                has_more = False,
                total_count = 2,
                limit = 10,
                offset = 0,
                data = [
                    asaas.models.fiscal_info_federal_service_code_response_dto.FiscalInfoFederalServiceCodeResponseDTO(
                        code = '040801', 
                        description = 'Terapia ocupacional', )
                    ]
            )
        else:
            return FiscalInfoFederalServiceCodeListResponseDTO(
        )
        """

    def testFiscalInfoFederalServiceCodeListResponseDTO(self):
        """Test FiscalInfoFederalServiceCodeListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
