# coding: utf-8

"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asaas.models.subscription_update_request_cycle import SubscriptionUpdateRequestCycle

class TestSubscriptionUpdateRequestCycle(unittest.TestCase):
    """SubscriptionUpdateRequestCycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionUpdateRequestCycle(self):
        """Test SubscriptionUpdateRequestCycle"""
        # inst = SubscriptionUpdateRequestCycle()

if __name__ == '__main__':
    unittest.main()
