"""
    Asaas

    API pública de integração com a plataforma Asaas.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from asaas.models.payment_split_get_full_response_dto import PaymentSplitGetFullResponseDTO
from asaas.models.payment_split_list_paid_request_payment_split_status import PaymentSplitListPaidRequestPaymentSplitStatus
from asaas.models.payment_split_list_received_request_payment_split_status import PaymentSplitListReceivedRequestPaymentSplitStatus
from asaas.models.payment_split_list_response_dto import PaymentSplitListResponseDTO

from asaas.api_client import ApiClient, RequestSerialized
from asaas.api_response import ApiResponse
from asaas.rest import RESTResponseType


class SplitsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def listar_splits_pagos(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="Elemento inicial da lista")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True)]], Field(description="Número de elementos da lista (max: 100)")] = None,
        payment_id: Annotated[Optional[StrictStr], Field(description="Filtrar pelo ID da cobrança")] = None,
        status: Annotated[Optional[PaymentSplitListPaidRequestPaymentSplitStatus], Field(description="Filtrar por status")] = None,
        payment_confirmed_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança inicial")] = None,
        payment_confirmed_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança final")] = None,
        credit_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de envio do split inicial")] = None,
        credit_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de envio do split final")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaymentSplitListResponseDTO:
        """Listar splits pagos

        

        :param offset: Elemento inicial da lista
        :type offset: int
        :param limit: Número de elementos da lista (max: 100)
        :type limit: int
        :param payment_id: Filtrar pelo ID da cobrança
        :type payment_id: str
        :param status: Filtrar por status
        :type status: PaymentSplitListPaidRequestPaymentSplitStatus
        :param payment_confirmed_date_ge: Filtrar a partir da data de confirmação da cobrança inicial
        :type payment_confirmed_date_ge: str
        :param payment_confirmed_date_le: Filtrar a partir da data de confirmação da cobrança final
        :type payment_confirmed_date_le: str
        :param credit_date_ge: Filtrar a partir da data de envio do split inicial
        :type credit_date_ge: str
        :param credit_date_le: Filtrar a partir da data de envio do split final
        :type credit_date_le: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._listar_splits_pagos_serialize(
            offset=offset,
            limit=limit,
            payment_id=payment_id,
            status=status,
            payment_confirmed_date_ge=payment_confirmed_date_ge,
            payment_confirmed_date_le=payment_confirmed_date_le,
            credit_date_ge=credit_date_ge,
            credit_date_le=credit_date_le,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitListResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def listar_splits_pagos_with_http_info(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="Elemento inicial da lista")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True)]], Field(description="Número de elementos da lista (max: 100)")] = None,
        payment_id: Annotated[Optional[StrictStr], Field(description="Filtrar pelo ID da cobrança")] = None,
        status: Annotated[Optional[PaymentSplitListPaidRequestPaymentSplitStatus], Field(description="Filtrar por status")] = None,
        payment_confirmed_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança inicial")] = None,
        payment_confirmed_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança final")] = None,
        credit_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de envio do split inicial")] = None,
        credit_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de envio do split final")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaymentSplitListResponseDTO]:
        """Listar splits pagos

        

        :param offset: Elemento inicial da lista
        :type offset: int
        :param limit: Número de elementos da lista (max: 100)
        :type limit: int
        :param payment_id: Filtrar pelo ID da cobrança
        :type payment_id: str
        :param status: Filtrar por status
        :type status: PaymentSplitListPaidRequestPaymentSplitStatus
        :param payment_confirmed_date_ge: Filtrar a partir da data de confirmação da cobrança inicial
        :type payment_confirmed_date_ge: str
        :param payment_confirmed_date_le: Filtrar a partir da data de confirmação da cobrança final
        :type payment_confirmed_date_le: str
        :param credit_date_ge: Filtrar a partir da data de envio do split inicial
        :type credit_date_ge: str
        :param credit_date_le: Filtrar a partir da data de envio do split final
        :type credit_date_le: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._listar_splits_pagos_serialize(
            offset=offset,
            limit=limit,
            payment_id=payment_id,
            status=status,
            payment_confirmed_date_ge=payment_confirmed_date_ge,
            payment_confirmed_date_le=payment_confirmed_date_le,
            credit_date_ge=credit_date_ge,
            credit_date_le=credit_date_le,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitListResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def listar_splits_pagos_without_preload_content(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="Elemento inicial da lista")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True)]], Field(description="Número de elementos da lista (max: 100)")] = None,
        payment_id: Annotated[Optional[StrictStr], Field(description="Filtrar pelo ID da cobrança")] = None,
        status: Annotated[Optional[PaymentSplitListPaidRequestPaymentSplitStatus], Field(description="Filtrar por status")] = None,
        payment_confirmed_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança inicial")] = None,
        payment_confirmed_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança final")] = None,
        credit_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de envio do split inicial")] = None,
        credit_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de envio do split final")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Listar splits pagos

        

        :param offset: Elemento inicial da lista
        :type offset: int
        :param limit: Número de elementos da lista (max: 100)
        :type limit: int
        :param payment_id: Filtrar pelo ID da cobrança
        :type payment_id: str
        :param status: Filtrar por status
        :type status: PaymentSplitListPaidRequestPaymentSplitStatus
        :param payment_confirmed_date_ge: Filtrar a partir da data de confirmação da cobrança inicial
        :type payment_confirmed_date_ge: str
        :param payment_confirmed_date_le: Filtrar a partir da data de confirmação da cobrança final
        :type payment_confirmed_date_le: str
        :param credit_date_ge: Filtrar a partir da data de envio do split inicial
        :type credit_date_ge: str
        :param credit_date_le: Filtrar a partir da data de envio do split final
        :type credit_date_le: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._listar_splits_pagos_serialize(
            offset=offset,
            limit=limit,
            payment_id=payment_id,
            status=status,
            payment_confirmed_date_ge=payment_confirmed_date_ge,
            payment_confirmed_date_le=payment_confirmed_date_le,
            credit_date_ge=credit_date_ge,
            credit_date_le=credit_date_le,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitListResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _listar_splits_pagos_serialize(
        self,
        offset,
        limit,
        payment_id,
        status,
        payment_confirmed_date_ge,
        payment_confirmed_date_le,
        credit_date_ge,
        credit_date_le,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if payment_id is not None:
            
            _query_params.append(('paymentId', payment_id))
            
        if status is not None:
            
            _query_params.append(('status', status.value))
            
        if payment_confirmed_date_ge is not None:
            
            _query_params.append(('paymentConfirmedDate[ge]', payment_confirmed_date_ge))
            
        if payment_confirmed_date_le is not None:
            
            _query_params.append(('paymentConfirmedDate[le]', payment_confirmed_date_le))
            
        if credit_date_ge is not None:
            
            _query_params.append(('creditDate[ge]', credit_date_ge))
            
        if credit_date_le is not None:
            
            _query_params.append(('creditDate[le]', credit_date_le))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Authorization'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v3/payments/splits/paid',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def listar_splits_recebidos(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="Elemento inicial da lista")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True)]], Field(description="Número de elementos da lista (max: 100)")] = None,
        payment_id: Annotated[Optional[StrictStr], Field(description="Filtrar pelo ID da cobrança")] = None,
        status: Annotated[Optional[PaymentSplitListReceivedRequestPaymentSplitStatus], Field(description="Filtrar por status")] = None,
        payment_confirmed_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança inicial")] = None,
        payment_confirmed_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança final")] = None,
        credit_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de recebimento do split inicial")] = None,
        credit_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de recebimento do split final")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaymentSplitListResponseDTO:
        """Listar splits recebidos

        

        :param offset: Elemento inicial da lista
        :type offset: int
        :param limit: Número de elementos da lista (max: 100)
        :type limit: int
        :param payment_id: Filtrar pelo ID da cobrança
        :type payment_id: str
        :param status: Filtrar por status
        :type status: PaymentSplitListReceivedRequestPaymentSplitStatus
        :param payment_confirmed_date_ge: Filtrar a partir da data de confirmação da cobrança inicial
        :type payment_confirmed_date_ge: str
        :param payment_confirmed_date_le: Filtrar a partir da data de confirmação da cobrança final
        :type payment_confirmed_date_le: str
        :param credit_date_ge: Filtrar a partir da data de recebimento do split inicial
        :type credit_date_ge: str
        :param credit_date_le: Filtrar a partir da data de recebimento do split final
        :type credit_date_le: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._listar_splits_recebidos_serialize(
            offset=offset,
            limit=limit,
            payment_id=payment_id,
            status=status,
            payment_confirmed_date_ge=payment_confirmed_date_ge,
            payment_confirmed_date_le=payment_confirmed_date_le,
            credit_date_ge=credit_date_ge,
            credit_date_le=credit_date_le,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitListResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def listar_splits_recebidos_with_http_info(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="Elemento inicial da lista")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True)]], Field(description="Número de elementos da lista (max: 100)")] = None,
        payment_id: Annotated[Optional[StrictStr], Field(description="Filtrar pelo ID da cobrança")] = None,
        status: Annotated[Optional[PaymentSplitListReceivedRequestPaymentSplitStatus], Field(description="Filtrar por status")] = None,
        payment_confirmed_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança inicial")] = None,
        payment_confirmed_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança final")] = None,
        credit_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de recebimento do split inicial")] = None,
        credit_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de recebimento do split final")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaymentSplitListResponseDTO]:
        """Listar splits recebidos

        

        :param offset: Elemento inicial da lista
        :type offset: int
        :param limit: Número de elementos da lista (max: 100)
        :type limit: int
        :param payment_id: Filtrar pelo ID da cobrança
        :type payment_id: str
        :param status: Filtrar por status
        :type status: PaymentSplitListReceivedRequestPaymentSplitStatus
        :param payment_confirmed_date_ge: Filtrar a partir da data de confirmação da cobrança inicial
        :type payment_confirmed_date_ge: str
        :param payment_confirmed_date_le: Filtrar a partir da data de confirmação da cobrança final
        :type payment_confirmed_date_le: str
        :param credit_date_ge: Filtrar a partir da data de recebimento do split inicial
        :type credit_date_ge: str
        :param credit_date_le: Filtrar a partir da data de recebimento do split final
        :type credit_date_le: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._listar_splits_recebidos_serialize(
            offset=offset,
            limit=limit,
            payment_id=payment_id,
            status=status,
            payment_confirmed_date_ge=payment_confirmed_date_ge,
            payment_confirmed_date_le=payment_confirmed_date_le,
            credit_date_ge=credit_date_ge,
            credit_date_le=credit_date_le,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitListResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def listar_splits_recebidos_without_preload_content(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="Elemento inicial da lista")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True)]], Field(description="Número de elementos da lista (max: 100)")] = None,
        payment_id: Annotated[Optional[StrictStr], Field(description="Filtrar pelo ID da cobrança")] = None,
        status: Annotated[Optional[PaymentSplitListReceivedRequestPaymentSplitStatus], Field(description="Filtrar por status")] = None,
        payment_confirmed_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança inicial")] = None,
        payment_confirmed_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de confirmação da cobrança final")] = None,
        credit_date_ge: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de recebimento do split inicial")] = None,
        credit_date_le: Annotated[Optional[StrictStr], Field(description="Filtrar a partir da data de recebimento do split final")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Listar splits recebidos

        

        :param offset: Elemento inicial da lista
        :type offset: int
        :param limit: Número de elementos da lista (max: 100)
        :type limit: int
        :param payment_id: Filtrar pelo ID da cobrança
        :type payment_id: str
        :param status: Filtrar por status
        :type status: PaymentSplitListReceivedRequestPaymentSplitStatus
        :param payment_confirmed_date_ge: Filtrar a partir da data de confirmação da cobrança inicial
        :type payment_confirmed_date_ge: str
        :param payment_confirmed_date_le: Filtrar a partir da data de confirmação da cobrança final
        :type payment_confirmed_date_le: str
        :param credit_date_ge: Filtrar a partir da data de recebimento do split inicial
        :type credit_date_ge: str
        :param credit_date_le: Filtrar a partir da data de recebimento do split final
        :type credit_date_le: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._listar_splits_recebidos_serialize(
            offset=offset,
            limit=limit,
            payment_id=payment_id,
            status=status,
            payment_confirmed_date_ge=payment_confirmed_date_ge,
            payment_confirmed_date_le=payment_confirmed_date_le,
            credit_date_ge=credit_date_ge,
            credit_date_le=credit_date_le,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitListResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _listar_splits_recebidos_serialize(
        self,
        offset,
        limit,
        payment_id,
        status,
        payment_confirmed_date_ge,
        payment_confirmed_date_le,
        credit_date_ge,
        credit_date_le,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if payment_id is not None:
            
            _query_params.append(('paymentId', payment_id))
            
        if status is not None:
            
            _query_params.append(('status', status.value))
            
        if payment_confirmed_date_ge is not None:
            
            _query_params.append(('paymentConfirmedDate[ge]', payment_confirmed_date_ge))
            
        if payment_confirmed_date_le is not None:
            
            _query_params.append(('paymentConfirmedDate[le]', payment_confirmed_date_le))
            
        if credit_date_ge is not None:
            
            _query_params.append(('creditDate[ge]', credit_date_ge))
            
        if credit_date_le is not None:
            
            _query_params.append(('creditDate[le]', credit_date_le))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Authorization'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v3/payments/splits/received',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def recuperar_um_unico_split_pago(
        self,
        id: Annotated[StrictStr, Field(description="Identificador único do split pago no Asaas")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaymentSplitGetFullResponseDTO:
        """Recuperar um único split pago

        

        :param id: Identificador único do split pago no Asaas (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._recuperar_um_unico_split_pago_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitGetFullResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '404': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def recuperar_um_unico_split_pago_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="Identificador único do split pago no Asaas")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaymentSplitGetFullResponseDTO]:
        """Recuperar um único split pago

        

        :param id: Identificador único do split pago no Asaas (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._recuperar_um_unico_split_pago_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitGetFullResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '404': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def recuperar_um_unico_split_pago_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="Identificador único do split pago no Asaas")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Recuperar um único split pago

        

        :param id: Identificador único do split pago no Asaas (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._recuperar_um_unico_split_pago_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitGetFullResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '404': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _recuperar_um_unico_split_pago_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Authorization'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v3/payments/splits/paid/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def recuperar_um_unico_split_recebido(
        self,
        id: Annotated[StrictStr, Field(description="Identificador único do split pago no Asaas")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaymentSplitGetFullResponseDTO:
        """Recuperar um único split recebido

        

        :param id: Identificador único do split pago no Asaas (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._recuperar_um_unico_split_recebido_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitGetFullResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '404': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def recuperar_um_unico_split_recebido_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="Identificador único do split pago no Asaas")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaymentSplitGetFullResponseDTO]:
        """Recuperar um único split recebido

        

        :param id: Identificador único do split pago no Asaas (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._recuperar_um_unico_split_recebido_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitGetFullResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '404': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def recuperar_um_unico_split_recebido_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="Identificador único do split pago no Asaas")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Recuperar um único split recebido

        

        :param id: Identificador único do split pago no Asaas (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._recuperar_um_unico_split_recebido_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentSplitGetFullResponseDTO",
            '401': "ErrorResponseDTO",
            '403': None,
            '404': None,
            '400': "ErrorResponseDTO",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _recuperar_um_unico_split_recebido_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Authorization'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v3/payments/splits/received/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


